#ifndef __CLIENTGAMEDEFINE_H__
#define __CLIENTGAMEDEFINE_H__

enum eGameInInitKind
{
	eGameInInitKind_Login,
	eGameInInitKind_MapChange,
	eGameInInitKind_SuryunEnter,
	eGameInInitKind_SuryunLeave,
	eGameInInitKind_MovePos,
	eGameInInitKind_EventMapEnter,
	eGameInInitKind_EventMapLeave,
	eGameInInitKind_GTEnter,
	eGameInInitKind_GTLeave,
	eGameInInitKind_GTObserverEnter,
	eGameInInitKind_SWEnter,
	eGameInInitKind_SWLeave,
	eGameInInitKind_SWObserverEnter,
	eGameInInitKind_SVMapLeave,
	//eGameInInitKind_UnionWarLeave,//[盟战][BY:十里坡剑神][QQ:112582793][2019-10-27][12:20:27]
};

typedef WORD	SNDIDX;

#define HEROID gHeroID
extern DWORD gHeroID;
extern DWORD gUserID;

extern DWORD gCurTime;
extern DWORD gTickTime;
extern float gTickPerFrame;
extern float gAntiGravity;
extern int gChannelNum;
extern bool IsBattleChannel[];
extern bool IsPeaceChannel[];
#define MAX_PLAYEROBJECT_NUM	500
#define MAX_MONSTEROBJECT_NUM	500
#define MAX_NPCOBJECT_NUM		100
#define MAX_TACTICOBJECT_NUM	100
#define MAX_PETOBJECT_NUM		300
#define MAX_MAPOBJECT_NUM		20

#define WEAPON_ATTACH_BONENAME_R	"Bone_R"
#define WEAPON_ATTACH_BONENAME_L	"Bone_L"
#define WEAPON_ATTACH_BONENAME_BACK	"Bone_Back"

#define MAX_MUNPA_PAGEBTN		9	
#define MAX_QUEST_PAGEBTN		5	
#define MAX_JOURNAL_PAGEBTN		5	
#define MAX_CHECKBOX_PERPAGE	5
enum wantnpcmode
{
	eWantNpcMode_Npc,
	eWantNpcMode_My,
	eWantNpcMode_Search,
	eWantNpcMode_Max
};
enum
{
	eDamageKind_Front = 1,
	eDamageKind_Left,
	eDamageKind_Right,
	
	eDamageKind_Counter,
	eDamageKind_ContinueDamage,
};

enum
{
	eRangeDamageKind_SameTime = 1,
	eRangeDamageKind_FrontToBack,
	eRangeDamageKind_LeftToRight,
	eRangeDamageKind_RightToLeft,
	eRangeDamageKind_CenterToEdge,
};

#define STREETSTALL_ENTER_DISTANCE		200

#define _CLIENT_RESOURCE_FIELD_			

#define DIRECTINPUT_VERSION		0x0800

enum MUNPALIST
{
	eMun_MunpaFamous, eMun_MunpaMemberNum, eMun_MunpaID
		
};

enum Wanted
{
	eWan_Date, eWan_Prize, eWan_Volunteer, eWan_OrderTypeMax,
};

enum guild_showmode
{
	eGuildMode_GuildInfo,
	eGuildMode_Func,
	eGuildMode_Max,
};

enum SuryunNpc_HyperLink
{
	eSuryunNpc_Suryun = 0,
	eSuryunNpc_About_GuildTournament,
	eSuryunNpc_Regist_GuildTournament,
	eSuryunNpc_Cancel_GuildTournament,
	eSuryunNpc_Show_GuildStand,
	eSuryunNpc_Enter_GuildTournament,
	eSuryunNpc_EnterObserver_GuildTournament,
	eSuryunNpc_SkillOption,
};

enum SiegeWar_NameBox
{
	eSiegeWarNameBox_CastleGuild = 0,
	eSiegeWarNameBox_SiegeGuild,
	eSiegeWarNameBox_Enermy,
};

#define MAX_PARSE_TYPE_NAME_LENGTH 40

enum PARSE_TYPE
{
	eDLG = 0,
	eCHARGUAGEDLG,
	eLISTDLG,
	eLISTDLGEX,
	eCHARINFODLG,
	eMUGONGSURYUNDLG,
	eMAINDLG,
	eINVENTORYDLG,
	eCHATDLG,
	eSTALLOPTIONDLG,
	eBUYSTALLDLG,
	eBUYREGDLG,
	eSTREETSTALLDLG,
	eNPCSCRIPTDLG,
	eHELPDLG,
	eCHARMAKEDLG,
	eHELPERSPEECHDLG,
	eMONEYDLG,
	eDEALDLG,
	eQUICKDIALOG,
	ePA_MEMBER1DLG,
	ePA_MEMBER2DLG,
	ePA_MEMBER3DLG,
	ePA_MEMBER4DLG,
	ePA_MEMBER5DLG,
	ePA_MEMBER6DLG,
	ePA_BTNDLG,
	ePA_CREATEDLG,
	ePA_INVITEDLG,
	eANI,
	eMOUSEPOINTER,
	ePYOGUKDLG,
	eFRIENDDLG,
	eNOTEDLG,
	eMINNOTEDLG,
	eMINFRIENDDLG,
	eREVIVEDLG,
	eCHANNELDLG,
	eWANTNPCDLG,
	eWANTREGISTDLG,
	eEXITDLG,
	eMACRODLG,
	eOPTIONDLG,
	eEXCHANGEDLG,
	eCHARSTATEDLG,
	eMENUSLOTDIALOG,
	ePKLOOTINGDLG,
	eCNADVICEDLG,
	eDISSOLUTIONDLG,
	eMNPLAYROOMDLG,
	eMNCHANNELDLG,
	eMINIMAPDLG,
	eBIGMAPDLG,
	eMONSTERGUAGEDLG,
	eDIVIDEBOX,
	eLOADINGDLG,
	eUPGRADEDLG,
	eMIXDLG,
	eREINFORCEDLG,
	eSERVERLISTDLG,
	eQUESTTOTALDLG,
	eMPREGISTDLG,
	eMPMISSIONDLG,
	eMPNOTICEDLG,
	eMPGUAGEDLG,
	eBAILDLG,
	eGMOPENTALKDLG,
	eGUILDCREATEDLG,
	eGUILDUNIONCREATEDLG,
	eGUILDDLG,
	eGUILDINVITEDlG,
	eGUILDMARKDLG,
	eGUILDLEVELUPDLG,
	eGUILDNICKNAMEDLG,
	eGUILDRANKDLG,
	eGUILDWAREHOUSEDLG,
	eITEMALLBASE,
	eSAVEMOVEDLG,
	eCHANGSAVEDLG,
	eGFWARDECLAREDLG,
	eGFWARRESULTDLG,
	eGFWARINFODLG,
	eGUILDWARINFODLG,
	eSKILLPOINTAGAINDLG,
	eSKILLPOINTOPDLG,
	ePARTYWARDLG,
	eCHALLWORLDCREATEDLG,
	eCHATALLDLG,
	eSEECHASEDLG,
	eCHASEDLG,
	eCHNAMECHANGEDLG,
	eOPCHNAMECHANGEDLG,
	eGDTENTRYDLG,
	eGDTENTRYCANCELDLG,
	eGDTOURNAMENTDLG,
	eGDTVIEWDLG,
	eEVENTMAPCOUNTDLG,
	eSEIGEWARTIMEREGDLG,
	eSEIGEWARPROTECTREGDLG,
	eSEIGEWARINFODLG,
	eSWSTARTTIMEDLG,
	eCHARCHANGEEDLG,
	eITEMLOCKDLG,
	eSWPROFITDLG,
	eENGRAVEDLG,
	eSWCOUNTDLG,
	eCHANGEJOBDLG,
	eRFDefaultDlg,
	eRareCreateDlg,
	ePETSTATEDLG,
	ePETSTATEMINIDLG,
	ePETINVENTORYDLG,
	ePETUPGRADEDLG,
	ePETREVIVALDLG,
	eRFDATAGUIDEDLG,
	eTIPBROWSERDLG,
	eKSDLG,
	eGUILDNOTEDLG,
	eALLYNOTEDLG,
	eGUILDNOTICEDLG,
	eGUILDPLUSTIMEDLG,
	eSkillTransDlg,
	eTDefaultDlg,
	eSCREENSHOTDLG,
	eJOINOPTIONDLG,
	eSURVCOUNTERDLG,
	eGUILDTRAINEEINFODLG,
	eGUILDTRAINEEDLG,
	eTITANPARTSMAKEDLG,
	eTITANMIXDLG,	
	eTITANUPGRADEDLG,
	eTITANBREAKDLG,
	eTITANPARTSCHANGEPREVIEWDLG,
	eTITAN_INVENTORY_DLG,
	eTITAN_GUAGE_DLG,
	eTITAN_MUGONGMIX_DLG,
	eTITAN_USE_DLG,
	eTITAN_BONGIN_DLG,
	eBTN,
	eEDITBOX,
	eSTATIC,
	ePUSHUPBTN,
	eCHECKBOX,
	eCOMBOBOX,
	eCOMBOBOXEX,
	eSPIN,
	eLISTCTRL,
	eLISTCTRLEX,
	eICONDLG,
	eICONGRIDDLG,	
	eWEAREDDLG,
	eLIST,
	eGUAGEBAR,
	eGUAGE,
	eTEXTAREA,
	eGUAGEN,
	eGUAGENE,
	eMUNPAMARKDLG,
	ePRIVATEWAREHOUSEDLG,
	eMUGONGDLG,
	eSURYUNDLG,
	eQUESTDLG,
	eWANTEDDLG,
	eJOURNALDLG,
	eITEMSHOPGRIDDLG,
	eSHOPITEMINVENGRID,
	ePOINT,
	ePOINT_,
	eFUNC,
	eID,
	eFONTIDX,
	eAUTOCLOSE,
	eTOOLTIPIMAGE,
	eTOOLTIPMSG,
	eTOOLTIPCOL,
	eTEXTXY,
	eMOVEABLE,
	eACTIVE,
	eBASICIMAGE,
	eBASICIMAGE_,
	eOVERIMAGE,
	eLISTOVERIMAGE,
	eSELECTIMAGE,
	ePRESSIMAGE,
	eFOCUSIMAGE,
	eBTNTEXT,
	eBTNTEXTANI,
	eIMAGESRCRECT,
	eALPHA,
	eEDITSIZE,
	eSPINSIZE,
	eSECRET,
	eTEXTCOLOR,
	eCOORD,
	eFGCOLOR,
	eTEXT,
	eITEMTOOLTIP,
	eSHADOW,
	eSHADOWCOLOR,
	eSHADOWTEXTXY,
	eMESSAGE,
	eTEXTRECT,
	ePUSHUP,
	eVALIDXY,
	eCAPTIONRECT,
	eICONCELLNUM,
	eICONCELL,
	eSELECTOPTION,
	eCELLRECT,
	eLIMITLINENUM,
	eLIMITBYTES,
	eTEXTALIGN,
	eAUTOSCROLL,
	ePASSIVE,
	eTABNUM,
	eICONCELLBGIMAGE,
	eDRAGOVERBGIMAGE,
	eCOLS,
	eROWS,
	eMIDDLENUM,
	eTOPIMAGE,
	eTOPHEIGHT,
	eDOWNHEIGHT,
	eMIDDELIMAGE,
	eMIDDLEHEIGHT,
	eDOWNIMAGE,
	eCOMBOTEXTCOLOR,
	eSELECTCOMBOINDEX,
	eREADONLY,
	eADDSTRING,
	eINITCOMBOLIST,
	eCREATE,
	eHEADIMAGE,
	eBODYIMAGE,
	eHEADHEIGHT,
	eBODYHEIGHT,
	eINSERTCOLUMN,
	eSETITEMTEXT,
	eSPINMINMAX,
	eSPINUNIT,
	eLINEUPWARD,
	eLISTBARINTERVAL,
	eLISTBARPOINT,
	eLISTBARIMAGE,
	eLISTMAXLINE,
	eLINEHEIGHT,
	eBTNCLICKSOUND,
	eMINMAXMIDDLENUM,
	eINITGRID,
	eINITGUAGEBAR,
	eMAXSPRITE,
	eSPRITELOOP,
	eTRAVELINGTYPE,
	eADDSPRITE,
	eGUAGEPIECEIMAGE,
	eGUAGEMINVALUE,
	eGUAGEMAXVALUE,
	eGUAGECURVALUE,
	eGUAGENEVALUE,
	eGUAGEPOS,
	eCHECKBOXIMAGE,
	eCHECKIMAGE,
	eSETCHECK,
	eSCALE,
	eLISTSCALE,
	eGUAGEWIDTH,
	eGUAGEPIECEWIDTH,
	eGUAGEEFFECTPIECEIMAGE,
	eGUAGEEFFECTPIECEWIDTH,
	eGUAGEPIECEHEIGHTSCALE,
	eGUAGEEFFECTPIECEHEIGHTSCALE,
	eBALLOONIMAGETOP,
	eBALLOONIMAGEMIDDLE,
	eBALLOONIMAGEBOTTOM,
	eBALLOONIMAGETAIL,
	eBALLOONIMAGEBORDER,
	eUNIQUEITEM_CURSECANCELLATION_DLG,
	eUNIQUEITEM_MIX_DLG,
	eSOS_DLG,
	eINTROREPLAY_DLG,
	eTITANREPAIR_DLG,
	eTITANRECALL_DLG,
	eUNIQUEITEMMIX_PROGRESSBAR_DLG,
	eTITANMIX_PROGRESSBAR_DLG,
	eTITANPARTS_PROGRESSBAR_DLG,
	eSKIN_SELECT_DLG,
    eSKILL_POINT_RESET_DLG,	
	eCOSTUMESKIN_SELECT_DLG,
	eSTALLVIEWDLG,			
	eSTALLFINDDLG,			
	ePARTYMATCHING_DLG,			
	eAUTONOTEDLG,			
	eAUTOANSWERDLG,			
	eFWENGRAVEDLG,			
	eFWTIMEDLG,
	eFWWAREHOUSEDLG,
	eMiniMarryDialog,      
	eControlDialog,        
	eOtherCharacterEquip,	
	eDIVIDEBOXEX, 
	eItemLockDLG,  
	eItemUnLockDLG,	
	eOnlineFame,		//[在线洗恶][By:十里坡剑神][QQ:112582793][2017/11/22]
	eGUILDBOARDDLG,		//[帮会排行][By:十里坡剑神][QQ:112582793][2017/11/26]
	eBillboardDialog,	//[角色排行][By:十里坡剑神][QQ:112582793][2017/11/26] 
	eREGDLG,			//[注册账号][By:十里坡剑神][QQ:112582793][2017/11/23]
	eRESTPWDDLG,		//[密码修改][By:十里坡剑神][QQ:112582793][2017/11/23]
	eCHARACTERRBTNDLG,	//[角色右键菜单][By:十里坡剑神][QQ:112582793][2017/11/23]
	eFBMAPTIPDLG,		//[副本地图剩余时间提示][By:十里坡剑神][QQ:112582793][2017/11/21]
	eOpenPyogukDlg,		//[开仓卷选择界面][By:十里坡剑神][QQ:112582793][2017/12/9]
	eSingedDlg,			//[签到系统][By:十里坡剑神][QQ:112582793][2018/1/4]
	eRechargeDlg,		//[充值礼包][By:十里坡剑神][QQ:112582793][2018/1/31]
	eSetingInfoDlg,		//[设置信息查看界面][By:十里坡剑神][QQ:112582793][2018/3/10]
	eStatuIcoBtnDlg,	//[状态图标隐藏按钮][By:十里坡剑神][QQ:112582793][2018/3/10]
	eTopRankDlg,		//[排名显示][By:十里坡剑神][QQ:112582793][2018/3/23]
	eInventoryRBTDlg,	//[背包右键菜单响应][By:十里坡剑神][QQ:112582793][2018/4/3]
	eSendItemInfoDlg,	//[发送物品信息窗口][By:十里坡剑神][QQ:112582793][2018/4/3]
	eKillBoardDlg,		//[击杀排行][By:十里坡剑神][QQ:112582793][2018/4/22]
	eSafeLockDlg,		//[安全锁][By:十里坡剑神][QQ:112582793][2018/4/30]
	eMainDlgHideBtn,	//[主界面隐藏按钮][By:十里坡剑神][QQ:112582793][2018/6/7]
	eMainDlgSafeBtn,	//[安全锁按钮][By:十里坡剑神][QQ:112582793][2018/6/9]
	eSafeLockMainDlg,	//[安全锁主界面][By:十里坡剑神][QQ:112582793][2018/6/10]
	eVideo_Capture_Dldg,	//[录像功能界面][By:十里坡剑神][QQ:112582793][2018/9/17]
	eGoldShopSubDlg,		//[新商城][By:十里坡剑神][QQ:112582793][2018/9/29]
	eGoldShopMainDlg,		//[新商城][By:十里坡剑神][QQ:112582793][2018/9/29]
	eShopItemInventPlusDlg,	//[ShopInventoryPlus][By:十里坡剑神][QQ:112582793][2018/10/9]
	eFastConfigPointDlg,	//[快速加点卷][BY:十里坡剑神][QQ:112582793][2019-4-5][16:58:26]
	eLotSplitItemDlg,		//[批量拆分][BY:十里坡剑神][QQ:112582793][2019-4-8][10:04:59]
	eVimuWithGoldDlg,		//[押注比武][BY:十里坡剑神][QQ:112582793][2019-4-20][22:45:25]
	eEquipItemInherit,		//[装备传承][BY:十里坡剑神][QQ:112582793][2019-8-22][13:26:31]
	eUnionWarInfoDlg,		//[盟战][BY:十里坡剑神][QQ:112582793][2019-10-28][23:37:33]
	eMAX_PARSETYPE_NUM, 
};
//////////////////////////////////////////////////////////////////////////
#endif //__CLIENTGAMEDEFINE_H__
