#ifndef __PROTOCOL_H__
#define __PROTOCOL_H__



enum MP_CATEGORY
{
	MP_SERVER = 1,	
	MP_POWERUP,
	MP_CHAR,
	MP_MAP,
	MP_ITEM,	
	MP_CHAT,
	MP_USERCONN,
	MP_MOVE,
	MP_MUGONG,
	MP_AUCTIONBOARD,
	MP_CHEAT,
	MP_QUICK,
	MP_PACKEDDATA,
	MP_PARTY,
	MP_PEACEWARMODE,
	MP_UNGIJOSIK,
	MP_AUCTION,
	MP_AUTOPATCH,	
	MP_SIGNAL,
	MP_TACTIC,
	MP_MUNPA,
	MP_SKILL,
	MP_KYUNGGONG,
	MP_SIMBUB,
	MP_MORNITORTOOL,
	MP_MORNITORSERVER,
	MP_MORNITORMAPSERVER,
	MP_EXCHANGE,
	MP_STREETSTALL,
	MP_PYOGUK,
	MP_BATTLE,
	MP_CHAR_REVIVE,
	MP_FRIEND,
	MP_BOSSMONSTER,
	MP_MONSTER,
	MP_OPTION,
	MP_NPC,
	MP_MURIMNET,
	MP_QUEST,		
	MP_DEBUG,
	MP_PK,	
	MP_HACKCHECK,
	/////////////////////
	MP_RMTOOL_CONNECT,
	MP_RMTOOL_USER,
	MP_RMTOOL_MUNPA,
	MP_RMTOOL_GAMELOG,
	MP_RMTOOL_OPERLOG,
	MP_RMTOOL_STATISTICS,
	MP_RMTOOL_ADMIN,
	MP_RMTOOL_CHARACTER, 
	MP_RMTOOL_ITEM,
	
	/////////////////////
	MP_WANTED,
	MP_JOURNAL,
	MP_SURYUN,
	MP_SOCIETYACT,
	MP_GUILD,
	MP_GUILD_FIELDWAR,
	MP_NOTE,
	MP_PARTYWAR,
	MP_GTOURNAMENT,
	MP_JACKPOT,
	MP_GUILD_UNION,
	MP_SIEGEWAR,
	MP_SIEGEWAR_PROFIT,
	MP_WEATHER,
	MP_PET,
	MP_HACKSHIELD,
	MP_RMTOOL_PET,
	MP_NPROTECT,
	MP_RMTOOL_DELCHAR,
	MP_SURVIVAL,
	MP_TITAN,
	MP_ITEMEXT,
	MP_BOBUSANG,
	MP_ITEMLIMIT,
	MP_AUTONOTE,
	MP_FORTWAR,
    MP_MARRY,   // marry protocol define 2014-05-09
	MP_SHITU,   // ShiTu Protocol define 2014-05-12
	MP_CLIENT,  // Client msg Protocol define 2014-05-25
	MP_SINGED,  //[签到系统][By:十里坡剑神][QQ:112582793][2018/1/4]
	MP_RECHARGE,  //[充值礼包][By:十里坡剑神][QQ:112582793][2018/1/31]
	MP_KILLTOPLIST,//[击杀排行信息][By:十里坡剑神][QQ:112582793][2018/4/22]
	MP_SAFELOCK,	//[安全锁][By:十里坡剑神][QQ:112582793][2018/4/30]
	RE_DIS_CONNECT,	//[断线重连消息][By:十里坡剑神][QQ:112582793][2018/6/12]
	MP_MAX,
};
 

enum MP_PROTOCOL_NPROTECT
{
	MP_NPROTECT_QUERY,
	MP_NPROTECT_ANSWER,
	MP_NPROTECT_DISCONNECT,
	MP_NPROTECT_USER_DISCONNECT,

	MP_NPROTECT_HACKTOOLUSER,
};

enum MP_PROTOCOL_HACKSHIELD
{
	MP_HACKSHIELD_GUID_REQ,
	MP_HACKSHIELD_GUID_ACK,
	MP_HACKSHIELD_REQ,
	MP_HACKSHIELD_ACK,
	MP_HACKSHIELD_DISCONNECT,
};

enum MP_PROTOCOL_WEATHER
{
	MP_WEATHER_SET,
	MP_WEATHER_EXE,
	MP_WEATHER_RETURN,
	MP_WEATHER_STATE,
};

enum MP_PROTOCOL_MORNITORTOOL 
{
	MP_MORNITORTOOL_EXECUTE_MAPSERVER_SYN,
	MP_MORNITORTOOL_EXECUTE_MAPSERVER_ACK,/*not used*/
	MP_MORNITORTOOL_EXECUTE_MAPSERVER_NACK,/*not used*/

	MP_MORNITORTOOL_SHUTDOWN_MAPSERVER_SYN,
	MP_MORNITORTOOL_SHUTDOWN_MAPSERVER_ACK,/*not used*/
	MP_MORNITORTOOL_SHUTDOWN_MAPSERVER_NACK,/*not used*/
	
	MP_MORNITORTOOL_NOTICESEND_SYN,
	MP_MORNITORTOOL_NOTICESEND_ACK,/*not used*/
	MP_MORNITORTOOL_NOTICESEND_NACK,/*not used*/

	MP_MORNITORTOOL_MAPSERVERSTATE_SYN,	
	MP_MORNITORTOOL_MAPSERVERSTATE_ACK,
	MP_MORNITORTOOL_MAPSERVERSTATE_NACK,

	MP_MORNITORTOOL_MAPSERVERSTATE_NOTIFY,

	MP_MORNITORTOOL_EXECUTE_AUTOPATCH_SYN,			// AutoPatch
	MP_MORNITORTOOL_CHANGE_USERLEVEL_SYN,			// UserLevel
	MP_MORNITORTOOL_CHANGE_USERLEVEL_ACK,
	MP_MORNITORTOOL_CHANGE_USERLEVEL_NACK,
	
	MP_MORNITORTOOL_QUERYUSERCOUNT_SYN,
	MP_MORNITORTOOL_QUERYUSERCOUNT_ACK,
	MP_MORNITORTOOL_QUERYUSERCOUNT_NACK,
	
	MP_MORNITORTOOL_ASSERTMSGBOX_SYN,

	MP_MORNITORTOOL_DISCONNECT_ALLUSER_SYN,		
	MP_MORNITORTOOL_DISCONNECT_ALLUSER_ACK,
	MP_MORNITORTOOL_DISCONNECT_ALLUSER_NACK,

	MP_MORNITORTOOL_QUERY_VERSION_SYN,			// version
	MP_MORNITORTOOL_QUERY_VERSION_ACK,
	MP_MORNITORTOOL_QUERY_VERSION_NACK,

	MP_MORNITORTOOL_CHANGE_VERSION_SYN,
	MP_MORNITORTOOL_CHANGE_VERSION_ACK,
	MP_MORNITORTOOL_CHANGE_VERSION_NACK,
	
	MP_MORNITORTOOL_QUERY_MAXUSER_SYN,
	MP_MORNITORTOOL_QUERY_MAXUSER_ACK,

	MP_MORNITORTOOL_CHANGE_MAXUSER_SYN,
	MP_MORNITORTOOL_CHANGE_MAXUSER_ACK,
	
	MP_MORNITORTOOL_MSSTATEALL_SYN,
	MP_MORNITORTOOL_MSSTATEALL_ACK,

	MP_MORNITORTOOL_CHECK_AUTOPATCH_ACK,
	MP_MORNITORTOOL_QUERY_AUTOPATCHVERSION_SYN,
	MP_MORNITORTOOL_QUERY_AUTOPATCHVERSION_ACK,
	
	MP_MORNITORTOOL_QUERY_CHANNELINFO_SYN,
	MP_MORNITORTOOL_QUERY_CHANNELINFO_ACK,
	
	MP_MORNITORTOOL_KILL_SERVER_SYN,

	MP_MORNITORTOOL_CONNECTED_SERVERLIST_SYN,
	MP_MORNITORTOOL_CONNECTED_SERVERLIST_ACK,
	
	MP_MORNITORTOOL_EVENTNOTICE_ON,
	MP_MORNITORTOOL_EVENTNOTICE_OFF,
};

enum MP_PROTOCOL_MORNITORSERVER
{
	MP_MORNITORSERVER_MSINFO_NOTIFY,
	MP_MORNITORSERVER_BOOTUP_NOTIFY,
	MP_MORNITORSERVER_BOOTLIST_NOTIFY,
	MP_MORNITORSERVER_EXECUTE_MAPSERVER_SYN,
	MP_MORNITORSERVER_EXECUTE_MAPSERVER_ACK,/*not used*/
	MP_MORNITORSERVER_EXECUTE_MAPSERVER_NACK,/*not used*/

	MP_MORNITORSERVER_SHUTDOWN_MAPSERVER_SYN,
	MP_MORNITORSERVER_SHUTDOWN_MAPSERVER_ACK,/*not used*/
	MP_MORNITORSERVER_SHUTDOWN_MAPSERVER_NACK,/*not used*/

	MP_MORNITORSERVER_NOTICESEND_SYN,
	MP_MORNITORSERVER_NOTICESEND_ACK,/*not used*/
	MP_MORNITORSERVER_NOTICESEND_NACK,/*not used*/

	MP_MORNITORSERVER_MAPSERVERSTATE_SYN,/*not used*/
	MP_MORNITORSERVER_MAPSERVERSTATE_ACK,/*ms->mas!!!!!!!!!!!*/
	MP_MORNITORSERVER_MAPSERVERSTATE_NACK,/*not used*/

	MP_MORNITORSERVER_EXECUTE_AUTOPATCH_SYN,	// AutoPatch
	MP_MORNITORSERVER_CHANGE_USERLEVEL_SYN,		// UserLevel
	MP_MORNITORSERVER_CHANGE_USERLEVEL_ACK,
	MP_MORNITORSERVER_CHANGE_USERLEVEL_NACK,
	
	MP_MORNITORSERVER_QUERYUSERCOUNT_SYN,
	MP_MORNITORSERVER_QUERYUSERCOUNT_ACK,
	MP_MORNITORSERVER_QUERYUSERCOUNT_NACK,
	
	MP_MORNITORSERVER_ASSERTMSGBOX_SYN,

	MP_MORNITORSERVER_DISCONNECT_ALLUSER_SYN,		
	MP_MORNITORSERVER_DISCONNECT_ALLUSER_ACK,
	MP_MORNITORSERVER_DISCONNECT_ALLUSER_NACK,

	MP_MORNITORSERVER_QUERY_VERSION_SYN,
	MP_MORNITORSERVER_QUERY_VERSION_ACK,
	MP_MORNITORSERVER_QUERY_VERSION_NACK,

	MP_MORNITORSERVER_CHANGE_VERSION_SYN,
	MP_MORNITORSERVER_CHANGE_VERSION_ACK,
	MP_MORNITORSERVER_CHANGE_VERSION_NACK,

	MP_MORNITORSERVER_QUERY_MAXUSER_SYN,
	MP_MORNITORSERVER_QUERY_MAXUSER_ACK,

	MP_MORNITORSERVER_CHANGE_MAXUSER_SYN,
	MP_MORNITORSERVER_CHANGE_MAXUSER_ACK,

	MP_MORNITORSERVER_CHECK_AUTOPATCH_ACK,
	MP_MORNITORSERVER_QUERY_AUTOPATCHVERSION_SYN,
	MP_MORNITORSERVER_QUERY_AUTOPATCHVERSION_ACK,

	MP_MORNITORSERVER_QUERY_CHANNELINFO_SYN,
	MP_MORNITORSERVER_QUERY_CHANNELINFO_ACK,

	MP_MORNITORSERVER_KILL_SERVER_SYN,

	MP_MORNITORSERVER_CONNECTED_SERVERLIST_SYN,
	MP_MORNITORSERVER_CONNECTED_SERVERLIST_ACK,

	MP_MORNITORSERVER_EVENTNOTICE_ON,
	MP_MORNITORSERVER_EVENTNOTICE_OFF,
};

enum MP_PROTOCOL_MORNITORMAPSERVER
{
	MP_MORNITORMAPSERVER_BOOTUP_NOTIFY,
	MP_MORNITORMAPSERVER_BOOTLIST_NOTIFY,
	MP_MORNITORMAPSERVER_EXECUTE_MAPSERVER_SYN,/*not used*/
	MP_MORNITORMAPSERVER_EXECUTE_MAPSERVER_ACK,/*not used*/
	MP_MORNITORMAPSERVER_EXECUTE_MAPSERVER_NACK,/*not used*/

	MP_MORNITORMAPSERVER_SHUTDOWN_MAPSERVER_SYN,/*not used*/
	MP_MORNITORMAPSERVER_SHUTDOWN_MAPSERVER_ACK,/*not used*/

	MP_MORNITORMAPSERVER_SHUTDOWN_MAPSERVER_NACK,/*not used*/

	MP_MORNITORMAPSERVER_NOTICESEND_SYN,
	MP_MORNITORMAPSERVER_NOTICESEND_ACK,/*not used*/
	MP_MORNITORMAPSERVER_NOTICESEND_NACK,/*not used*/

	MP_MORNITORMAPSERVER_PING_SYN,
	MP_MORNITORMAPSERVER_PING_ACK,

	MP_MORNITORMAPSERVER_CHANGE_USERLEVEL_SYN,

	MP_MORNITORMAPSERVER_CHANGE_USERLEVEL_ACK,
	MP_MORNITORMAPSERVER_CHANGE_USERLEVEL_NACK,

	MP_MORNITORMAPSERVER_QUERYUSERCOUNT_SYN,
	MP_MORNITORMAPSERVER_QUERYUSERCOUNT_ACK,
	MP_MORNITORMAPSERVER_QUERYUSERCOUNT_NACK,

	MP_MORNITORMAPSERVER_ASSERTMSGBOX_SYN,
	
	MP_MORNITORMAPSERVER_DISCONNECT_ALLUSER_SYN, 
	MP_MORNITORMAPSERVER_DISCONNECT_ALLUSER_ACK,
	MP_MORNITORMAPSERVER_DISCONNECT_ALLUSER_NACK,

	MP_MORNITORMAPSERVER_SERVEROFF_SYN,

	MP_MORNITORMAPSERVER_QUERY_VERSION_SYN,
	MP_MORNITORMAPSERVER_QUERY_VERSION_ACK,
	MP_MORNITORMAPSERVER_QUERY_VERSION_NACK,

	MP_MORNITORMAPSERVER_CHANGE_VERSION_SYN,
	MP_MORNITORMAPSERVER_CHANGE_VERSION_ACK,
	MP_MORNITORMAPSERVER_CHANGE_VERSION_NACK,

	MP_MORNITORMAPSERVER_QUERY_MAXUSER_SYN,
	MP_MORNITORMAPSERVER_QUERY_MAXUSER_ACK,

	MP_MORNITORMAPSERVER_CHANGE_MAXUSER_SYN,
	MP_MORNITORMAPSERVER_CHANGE_MAXUSER_ACK,

	MP_MORNITORMAPSERVER_QUERY_CHANNELINFO_SYN,
	MP_MORNITORMAPSERVER_QUERY_CHANNELINFO_ACK, 

	MP_MORNITORMAPSERVER_KILL_SERVER_SYN,	

	MP_MORNITORMAPSERVER_CONNECTED_SERVERLIST_SYN,
	MP_MORNITORMAPSERVER_CONNECTED_SERVERLIST_ACK,	

	MP_MORNITORMAPSERVER_EVENTNOTICE_ON,
	MP_MORNITORMAPSERVER_EVENTNOTICE_OFF,
};

enum MP_PROTOCOL_AUTOPATCH
{
	MP_AUTOPATCH_TRAFFIC_SYN,
	MP_AUTOPATCH_TRAFFIC_ACK,
	MP_AUTOPATCH_TRAFFIC_NACK,
};
enum MP_PROTOCOL_AUCTION
{
	MP_AUCTION_SUCCESS_SYN,
	MP_AUCTION_SUCCESS_ACK,
	MP_AUCTION_SUCCESS_NACK,

	MP_AUCTION_SEARCH_SYN,
	MP_AUCTION_SEARCH_ACK,
	MP_AUCTION_SEARCH_NACK,

	MP_AUCTION_SORT_SYN,
	MP_AUCTION_SORT_ACK,
	MP_AUCTION_SORT_NACK,

	MP_AUCTION_REGISTER_OK_SYN,
	MP_AUCTION_REGISTER_OK_ACK,
	MP_AUCTION_REGISTER_OK_NACK,
	
	MP_AUCTION_REGISTSER_CANCEL_SYN,
	MP_AUCTION_REGISTSER_CANCEL_ACK,
	MP_AUCTION_REGISTSER_CANCEL_NACK,

	MP_AUCTION_JOIN_OK_SYN,
	MP_AUCTION_JOIN_OK_ACK,
	MP_AUCTION_JOIN_OK_NACK,

	MP_AUCTION_CANCEL_SYN,
	MP_AUCTION_CANCEL_ACK,
	MP_AUCTION_CANCEL_NACK,
};

enum MP_PROTOCOL_SERVER
{
	MP_SERVER_PWRUP,
	MP_SERVER_MSG,
	MP_SERVER_USERCNT,

	MP_SERVER_CONNECT_SUCCESS,
	MP_SERVER_REGISTMAP_SYN,
	MP_SERVER_REGISTMAP_ACK,

	MP_SERVER_AGENTDISABLE,
	
	MP_SERVER_TEST_PROTOCOL,
};
enum MP_PROTOCOL_POWERUP
{
	MP_POWERUP_BOOTING_NOTIFY,	
	MP_POWERUP_BOOTLIST_SYN,	
	MP_POWERUP_BOOTLIST_ACK,	
	MP_POWERUP_CONNECT_SYN,	
	MP_POWERUP_CONNECT_ACK,
};
enum MP_PROTOCOL_CHAR
{
	MP_CHAR_LIFE_SYN,			
	MP_CHAR_LIFE_ACK,
	MP_CHAR_LIFE_NACK,
	MP_CHAR_MAXLIFE_NOTIFY,
		
	MP_CHAR_SHIELD_SYN,			
	MP_CHAR_SHIELD_ACK,
	MP_CHAR_SHIELD_NACK,
	MP_CHAR_MAXSHIELD_NOTIFY,

	MP_CHAR_NAERYUK_SYN,	
	MP_CHAR_NAERYUK_ACK,
	MP_CHAR_NAERYUK_NACK,
	MP_CHAR_MAXNAERYUK_NOTIFY,

	MP_CHAR_EXPPOINT_SYN,		
	MP_CHAR_EXPPOINT_ACK,
	MP_CHAR_EXPPOINT_NACK,

	MP_CHAR_GENGOL_NOTIFY,
	MP_CHAR_MINCHUB_NOTIFY,
	MP_CHAR_SIMMEK_NOTIFY,
	MP_CHAR_CHERYUK_NOTIFY,


	MP_CHAR_LEVEL_NOTIFY,
	MP_CHAR_PLAYERLEVELUP_NOTIFY,
	
	MP_CHAR_POINTADD_SYN,
	MP_CHAR_POINTADD_ACK,
	MP_CHAR_POINTADD_NACK,
	
	MP_CHAR_LEVELUPPOINT_NOTIFY,

	MP_CHAR_FAME_NOTIFY,
	
	MP_CHAR_STATE_NOTIFY,

	MP_CHAR_LIFE_NOTIFY,
	
	MP_CHAR_ABILITYEXPPOINT_SYN,	
	MP_CHAR_ABILITYEXPPOINT_ACK,
	MP_CHAR_ABILITYEXPPOINT_NACK,
	
	MP_CHAR_ABILITY_UPGRADE_SYN,
	MP_CHAR_ABILITY_UPGRADE_ACK,
	MP_CHAR_ABILITY_UPGRADE_NACK,

	MP_CHAR_YOUAREDIED,
	
	MP_CHAR_EXITSTART_SYN,
	MP_CHAR_EXITSTART_ACK,
	MP_CHAR_EXITSTART_NACK,

	MP_CHAR_EXIT_SYN,
	MP_CHAR_EXIT_ACK,
	MP_CHAR_EXIT_NACK,

	MP_CHAR_BADFAME_NOTIFY,
	MP_CHAR_BADFAME_SYN,
	MP_CHAR_BADFAME_ACK,
	MP_CHAR_BADFAME_NACK,
	MP_CHAR_BADFAME_CHANGED,

	MP_CHAR_PLAYTIME_SYN,
	MP_CHAR_PLAYTIME_ACK,
	MP_CHAR_PLAYTIME_NACK,

	MP_CHAR_POINTMINUS_SYN,
	MP_CHAR_POINTMINUS_ACK,
	MP_CHAR_POINTMINUS_NACK,

	MP_CHAR_ABILITY_UPGRADE_SKPOINT_SYN,
	MP_CHAR_ABILITY_UPGRADE_SKPOINT_ACK,
	MP_CHAR_ABILITY_UPGRADE_SKPOINT_NACK,
	MP_CHAR_ABILITY_DOWNGRADE_SKPOINT_SYN,
	MP_CHAR_ABILITY_DOWNGRADE_SKPOINT_ACK,
	MP_CHAR_ABILITY_DOWNGRADE_SKPOINT_NACK,

	MP_CHAR_STAGE_NOTIFY,
	MP_CHAR_CHANGE_SUBATTR_ACK,
	MP_CHAR_CHANGE_SUBATTR_NACK,
	
	MP_CHAR_MUSSANG_SYN,
	MP_CHAR_MUSSANG_ACK,
	MP_CHAR_MUSSANG_NACK,
	MP_CHAR_MUSSANG_INFO,
	MP_CHAR_MUSSANG_END,

	MP_CHAR_SINGLE_SPECIAL_STATE_NOTIFY,
	MP_CHAR_SINGLE_SPECIAL_STATE_ACK,
	MP_CHAR_SINGLE_SPECIAL_STATE_NACK,

	MP_CHAR_FULLMOONEVENT_CHANGE,

	MP_CHAR_NOACTIONPANELTY_NOTIFY,

	MP_CHAR_ABILITY_RESET_SKPOINT_SYN,
	MP_CHAR_ABILITY_RESET_SKPOINT_ACK,
	MP_CHAR_ABILITY_RESET_SKPOINT_NACK,

	// 2014-05-05 ChangeLife  Stage Protect Define!

	MP_CHAR_CHANGESTAGE_SYN,
	MP_CHAR_CHANGESTAGE_ACK,
	MP_CHAR_CHANGESTAGE_NACK,

	MP_CHAR_CHANGELIFE_SYN,
	MP_CHAR_CHANGELIFE_ACK,
	MP_CHAR_CHANGELIFE_NACK,
	MP_CHAR_CHANGELIFE_INFO_SYN,
	MP_CHAR_CHANGELIFE_INFO_ACK,


	// 2014-11-12 Ping 

	MP_CHAR_PING_SYN,
    MP_CHAR_PING_ACK,
	MP_CHAR_PING_NACK,

	MP_CHAR_BASICPOINT_NOTIFY,
	//[自动加点请求协议][By:十里坡剑神][QQ:112582793][2018/4/17]
	MP_CHAR_AUTOADD_SYN,
};

enum MP_PROTOCOL_USERCONN
{
	MP_USERCONN_DIST_CONNECTSUCCESS,			
	
	MP_USERCONN_LOGIN_SYN,							

	MP_USERCONN_LOGIN_ACK,							
	MP_USERCONN_LOGIN_NACK,

	MP_USERCONN_NOTIFY_USERLOGIN_SYN,	
	MP_USERCONN_NOTIFY_USERLOGIN_ACK,	
	MP_USERCONN_NOTIFY_USERLOGIN_NACK,	
	MP_USERCONN_NOTIFY_OVERLAPPEDLOGIN,					
	MP_USERCONN_AGENT_CONNECTSUCCESS,				

	MP_USERCONN_CHARACTERLIST_SYN,				
	MP_USERCONN_DIRECTCHARACTERLIST_SYN,			
	MP_USERCONN_CHARACTERLIST_NACK,	
	MP_USERCONN_CHARACTERLIST_ACK,
	
	MP_USERCONN_DISCONNECT_SYN,						
	MP_USERCONN_DISCONNECT_ACK,
	MP_USERCONN_DISCONNECT_NACK,

	MP_USERCONN_CHARACTERSELECT_SYN,				
	MP_USERCONN_CHARACTERSELECT_ACK,				
	MP_USERCONN_CHARACTERSELECT_NACK,

	MP_USERCONN_CHARACTER_NAMECHECK_SYN,			
	MP_USERCONN_CHARACTER_NAMECHECK_ACK,
	MP_USERCONN_CHARACTER_NAMECHECK_NACK,

	MP_USERCONN_CHARACTER_MAKE_SYN,					
	MP_USERCONN_CHARACTER_MAKE_ACK,					
	MP_USERCONN_CHARACTER_MAKE_NACK,

	MP_USERCONN_CHARACTER_INFO_SYN,					
	MP_USERCONN_CHARACTER_INFO_ACK,
	MP_USERCONN_CHARACTER_INFO_NACK,

	MP_USERCONN_GAMEIN_SYN,						
	MP_USERCONN_GAMEIN_ACK,
	MP_USERCONN_GAMEIN_NACK,

	MP_USERCONN_GAMEOUT_SYN,						
	MP_USERCONN_GAMEOUT_ACK,
	MP_USERCONN_GAMEOUT_NACK,

	MP_USERCONN_DISCONNECTED,		
	
	MP_USERCONN_CHARACTER_ADD,
	MP_USERCONN_PET_ADD,
	MP_USERCONN_MONSTER_ADD,
	MP_USERCONN_BOSSMONSTER_ADD, 
	MP_USERCONN_NPC_ADD,
	MP_USERCONN_OBJECT_REMOVE,
	
	MP_USERCONN_CHARACTER_DIE,			
	MP_USERCONN_MONSTER_DIE,			
	MP_USERCONN_PET_DIE,

	MP_USERCONN_CHARACTER_REVIVE,
 
	MP_USERCONN_CHARACTER_REMOVE_SYN,		
	MP_USERCONN_CHARACTER_REMOVE_ACK,
	MP_USERCONN_CHARACTER_REMOVE_NACK,

	MP_USERCONN_CHANGEMAP_SYN,			
	MP_USERCONN_CHANGEMAP_ACK,
	MP_USERCONN_CHANGEMAP_NACK,
	MP_USERCONN_MAP_OUT,
	MP_USERCONN_MAP_OUT_WITHMAPNUM,
		
	MP_USERCONN_CHARACTER_TOTALINFO,

	MP_USERCONN_SAVEPOINT_SYN,			
	MP_USERCONN_SAVEPOINT_ACK,			
	MP_USERCONN_SAVEPOINT_NACK,
	
	MP_USERCONN_BACKTOCHARSEL_SYN,
	MP_USERCONN_BACKTOCHARSEL_ACK,
	MP_USERCONN_BACKTOCHARSEL_NACK,
	
	MP_USERCONN_GRIDINIT,
	
	MP_USERCONN_SETVISIBLE,
	MP_USERCONN_OTHERUSER_CONNECTTRY_NOTIFY,
	
	MP_USERCONN_CONNECTION_CHECK,		
	MP_USERCONN_CONNECTION_CHECK_OK,
	
	MP_USERCONN_CHECKSUMERROR,
	
	MP_USERCONN_FORCE_DISCONNECT_OVERLAPLOGIN,
	MP_USERCONN_DISCONNECTED_BY_OVERLAPLOGIN,
	
	MP_USERCONN_CHANNELINFO_SYN,
	MP_USERCONN_CHANNELINFO_ACK,
	MP_USERCONN_CHANNELINFO_NACK,

	MP_USERCONN_NOTIFYTOAGENT_ALREADYOUT,	
	MP_USERCONN_REQUEST_DISTOUT,			

	MP_USERCONN_DISCONNECTED_ON_LOGIN,		

	MP_USERCONN_SERVER_NOTREADY,			
	MP_USERCONN_MAPDESC,					
	MP_USERCONN_CHARACTER_REVIVE_NACK,		

	MP_USERCONN_READY_TO_REVIVE,
	
	MP_USERCONN_CHEAT_USING,
	
	MP_USERCONN_CHEAT_CHANGEMAP_ACK,	

	MP_USERCONN_USE_DYNAMIC_SYN,						
	MP_USERCONN_USE_DYNAMIC_ACK,							
	MP_USERCONN_USE_DYNAMIC_NACK,

	MP_USERCONN_LOGIN_DYNAMIC_SYN,							
	MP_USERCONN_LOGIN_DYNAMIC_ACK,							
	MP_USERCONN_LOGIN_DYNAMIC_NACK,

	MP_USERCONN_LOGINCHECK_DELETE,
	MP_USERCONN_FORCE_DISCONNECT_OVERLAPLOGIN_ACK,

	MP_USERCONN_MAP_OUT_TO_EVENTMAP,	
	MP_USERCONN_MAP_OUT_TO_EVENTBEFOREMAP,
	MP_USERCONN_ENTER_EVENTMAP_SYN,	
	MP_USERCONN_EVENT_READY,
	MP_USERCONN_EVENT_START,	
	MP_USERCONN_EVENT_END,

	MP_USERCONN_EVENTITEM_USE,			
	MP_USERCONN_EVENTITEM_USE2,

	MP_USERCONN_GAMEINPOS_SYN,
	MP_USERCONN_GAMEINPOS_ACK,
	MP_USERCONN_GAMEINPOS_NACK,

	MP_USERCONN_REMAINTIME_NOTIFY,
	
	MP_USERCONN_BACKTOBEFOREMAP_TOUSER,
	MP_USERCONN_BACKTOBEFOREMAP_SYN,
	MP_USERCONN_BACKTOBEFOREMAP_ACK,
	MP_USERCONN_BACKTOBEFOREMAP_NACK,	

	MP_USERCONN_ENTER_GTOURNAMENT_SYN,
	
	MP_USERCONN_CHARACTERSLOT,	

	MP_USERCONN_CASTLEGATE_ADD,

	MP_USERCONN_GAMEIN_OTHERMAP_SYN,	
	MP_USERCONN_NOWAITEXITPLAYER,

	MP_USERCONN_FLAGNPC_ONOFF,			
	MP_USERCONN_LOGIN_SYN_BUDDY,

	MP_USERCONN_CHANGEMAP_CHANNELINFO_SYN,
	MP_USERCONN_CHANGEMAP_CHANNELINFO_ACK,
	MP_USERCONN_CHANGEMAP_CHANNELINFO_NACK,

	MP_USERCONN_CURRENTMAP_CHANNELINFO,
	//[注册帐号请求协议][By:十里坡剑神][QQ:112582793][2017/11/23]
	MP_USERCONN_REGUSER_SYN,	
	MP_USERCONN_REGUSER_ACK,
	//[修改密码请求协议][By:十里坡剑神][QQ:112582793][2017/11/23]
	MP_USERCONN_RESTPWD_SYN,	
	MP_USERCONN_RESTPWD_ACK,
	//[排行榜协议][By:十里坡剑神][QQ:112582793][2017/11/23]
	MP_TOPLIST_HERO_SYN,
	MP_TOPLIST_GUILD_SYN,

	MP_TOPLIST_KILLER_SYN,
	MP_TOPLIST_HERO_B_SYN,
	MP_TOPLIST_GUILD_B_SYN,
	MP_TOPLIST_KILLER_B_SYN,
	MP_TOPLIST_ACK,
	//[副本协议定义][By:十里坡剑神][QQ:112582793][2018/10/11]
	MP_CHAR_FB_SYN,
	MP_CHAR_FB_ACK,
	MP_CHAR_FB_NACK,
	MP_CHAR_FB_IN_ACK,
	//[比例设置文件重加载][By:十里坡剑神][QQ:112582793][2018/10/11]
	MP_USERCONN_RLOAD,
	MP_USERCONN_SET,
	MP_USERCONN_GET,
};

enum MP_PROTOCOL_MUGONG
{
	MP_MUGONG_TOTALINFO_LOCAL,				
	MP_MUGONG_MOVE_SYN,
	MP_MUGONG_MOVE_ACK,
	MP_MUGONG_MOVE_NACK,
	MP_MUGONG_REM_SYN,
	MP_MUGONG_REM_ACK,
	MP_MUGONG_REM_NACK,
	MP_MUGONG_ADD_SYN,			
	MP_MUGONG_ADD_ACK,
	MP_MUGONG_ADD_NACK,

	MP_MUGONG_EXPPOINT_NOTIFY,
	MP_MUGONG_SUNG_NOTIFY,
	MP_MUGONG_SUNG_LEVELUP,

	MP_MUGONG_OPTION_SYN,
	MP_MUGONG_OPTION_ACK,
	MP_MUGONG_OPTION_NACK,

	MP_MUGONG_OPTION_CLEAR_SYN,
	MP_MUGONG_OPTION_CLEAR_ACK,
	MP_MUGONG_OPTION_CLEAR_NACK,
};

enum MP_PROTOCOL_CHAT
{
	MP_CHAT_ALL,
	MP_CHAT_PARTY,
	MP_CHAT_GUILD,
	MP_CHAT_WHISPER,
	MP_CHAT_WHISPER_SYN,
	MP_CHAT_WHISPER_ACK,
	MP_CHAT_WHISPER_NACK,
	MP_CHAT_FROMMONSTER_ALL,
	MP_CHAT_MONSTERSPEECH,
	

	MP_CHAT_FASTCHAT,	
	MP_CHAT_GM,
	MP_CHAT_WHISPER_GM,		
	MP_CHAT_WHISPER_GM_SYN,

	MP_CHAT_SMALLSHOUT,		
	MP_CHAT_GM_SMALLSHOUT,
	
	MP_CHAT_SHOUT_SYN,
	MP_CHAT_SHOUT_ACK,
	MP_CHAT_SHOUT_NACK,
	MP_CHAT_SHOUT_SENDALL,
	MP_CHAT_SHOUT_SENDSERVER,
	
	MP_CHAT_GUILDUNION,
};

enum MP_PROTOCOL_MOVE
{
	MP_MOVE_INIT,
	MP_MOVE_TARGET,
	MP_MOVE_CORRECTION,
	
	MP_MOVE_WALKMODE,
	MP_MOVE_RUNMODE,

	MP_MOVE_KYUNGGONG_SYN,
	MP_MOVE_KYUNGGONG_ACK,
	MP_MOVE_KYUNGGONG_NACK,
	
	MP_MOVE_STOP,
	
	MP_MOVE_EFFECTMOVE,

	MP_MOVE_MONSTERMOVE_NOTIFY,

	MP_MOVE_FORCESTOPKYUNGGONG,
	
	MP_MOVE_WARP,

	MP_MOVE_ONETARGET,
	MP_MOVE_PET_ONETARGET,
	MP_MOVE_PET_TARGET,
	MP_MOVE_PET_STOP,
	MP_MOVE_PET_CORRECTION,
	MP_MOVE_PET_WARP_SYN,
	MP_MOVE_PET_WARP_ACK,

};

enum MP_PROTOCOL_ITEM
{
	MP_ITEM_TOTALINFO_LOCAL,
	MP_ITEM_PYOGUKITEM_INFO,  

	MP_ITEM_USE_SYN,
	MP_ITEM_USE_ACK,
	MP_ITEM_USE_NACK,

	MP_ITEM_COMBINE_SYN,
	MP_ITEM_COMBINE_ACK,
	MP_ITEM_COMBINE_NACK,
	MP_ITEM_DIVIDE_SYN,
	MP_ITEM_DIVIDE_ACK,
	MP_ITEM_DIVIDE_NACK,
	MP_ITEM_DIVIDE_NEWITEM_NOTIFY,
	MP_ITEM_DISCARD_SYN,
	MP_ITEM_DISCARD_ACK,
	MP_ITEM_DISCARD_NACK,

	MP_ITEM_ERROR_NACK,

	MP_ITEM_MOVE_SYN,
	MP_ITEM_MOVE_ACK,
	MP_ITEM_MOVE_NACK,
	
	MP_ITEM_BUY_SYN,
	MP_ITEM_BUY_ACK,
	MP_ITEM_BUY_NACK,

    MP_ITEM_MALL_MONEY,
	MP_ITEM_GOLD_MONEY,
	MP_ITEM_SW_MONEY,

    MP_ITEM_LOCKEX_SYN,
	MP_ITEM_LOCKEX_ACK,
	MP_ITEM_LOCKEX_NACK,

    MP_ITEM_UNLOCKEX_SYN,
	MP_ITEM_UNLOCKEX_ACK,
	MP_ITEM_UNLOCKEX_NACK,

	MP_ITEM_GROW_SYN,
	MP_ITEM_GROW_ACK,
	MP_ITEM_GROW_NACK,
	
	MP_ITEM_SELL_SYN,
	MP_ITEM_SELL_ACK,
	MP_ITEM_SELL_NACK,
	
	MP_ITEM_DEALER_SYN,		
	MP_ITEM_DEALER_ACK,
	MP_ITEM_DEALER_NACK,
	
	MP_ITEM_MONEY,
	MP_ITEM_MONEY_ERROR,
	
	MP_ITEM_APPEARANCE_CHANGE,
	
	MP_ITEM_OBTAIN_MONEY,			
	MP_ITEM_MONSTER_OBTAIN_NOTIFY,
	MP_ITEM_UPGRADE_SYN,
	MP_ITEM_UPGRADE_SUCCESS_ACK, 
	MP_ITEM_UPGRADE_FAILED_ACK, 
	MP_ITEM_UPGRADE_NACK,
	MP_ITEM_MIX_SYN,
	MP_ITEM_MIX_SUCCESS_ACK, 
	MP_ITEM_MIX_BIGFAILED_ACK,
	MP_ITEM_MIX_FAILED_ACK, 
	MP_ITEM_MIX_MSG,

	MP_ITEM_REINFORCE_SYN,
	MP_ITEM_REINFORCE_SUCCESS_ACK,
	MP_ITEM_REINFORCE_FAILED_ACK,
	MP_ITEM_REINFORCE_NACK,

	MP_ITEM_DISSOLVE_SYN,
	MP_ITEM_DISSOLVE_SUCCESS_ACK,
	MP_ITEM_DISSOLVE_FAILED_ACK,
	MP_ITEM_DISSOLVE_NACK,

	MP_ITEM_MUNPA_COMBINE_SYN,
	MP_ITEM_MUNPA_COMBINE_ACK,
	MP_ITEM_MUNPA_COMBINE_NACK,
	
	MP_ITEM_MUNPA_MOVE_SYN,
	MP_ITEM_MUNPA_MOVE_ACK,
	MP_ITEM_MUNPA_MOVE_NACK,

	MP_ITEM_MUNPA_WAREHOUSE_INFO_SYN,
	MP_ITEM_MUNPA_WAREHOUSE_INFO_ACK,
	MP_ITEM_MUNPA_WAREHOUSE_INFO_NACK,
	
	MP_ITEM_ADDTO_MUNPAWARE_NOTIFY,
	MP_ITEM_DELETEFROM_MUNPAWARE_NOTIFY,

	MP_ITEM_MUNPA_WAREHOUSE_LEAVE,
	
	MP_ITEM_PYOGUK_MOVE_SYN,
	MP_ITEM_PYOGUK_MOVE_ACK,
	MP_ITEM_PYOGUK_MOVE_NACK,

	MP_ITEM_PYOGUK_COMBINE_SYN,
	MP_ITEM_PYOGUK_COMBINE_ACK,
	MP_ITEM_PYOGUK_COMBINE_NACK,

	MP_ITEM_PYOGUK_ITEM_INFO_SYN,
	MP_ITEM_PYOGUK_ITEM_INFO_ACK,
	MP_ITEM_PYOGUK_ITEM_INFO_NACK,

	MP_ITEM_MIX_ADDITEM_SYN,
	MP_ITEM_MIX_ADDITEM_ACK,
	MP_ITEM_MIX_ADDITEM_NACK,

	MP_ITEM_MIX_RELEASEITEM,

	MP_ITEM_USE_FOR_QUESTSTART_SYN,
	MP_ITEM_USE_FOR_QUESTSTART_ACK,
	MP_ITEM_USE_FOR_QUESTSTART_NACK,
	
	MP_ITEM_DISSOLUTION_SYN,
	MP_ITEM_DISSOLUTION_ACK,
	MP_ITEM_DISSOLUTION_NACK,
	MP_ITEM_DISSOLUTION_GETITEM,

	MP_ITEM_USE_CHANGEITEM_SYN,	
	MP_ITEM_USE_CHANGEITEM_ACK,
	MP_ITEM_USE_CHANGEITEM_NACK,

	MP_ITEM_GUILD_COMBINE_SYN,
	MP_ITEM_GUILD_COMBINE_ACK,
	MP_ITEM_GUILD_COMBINE_NACK,
	
	MP_ITEM_GUILD_MOVE_SYN,
	MP_ITEM_GUILD_MOVE_ACK,
	MP_ITEM_GUILD_MOVE_NACK,

	MP_ITEM_GUILD_WAREHOUSE_INFO_SYN,
	MP_ITEM_GUILD_WAREHOUSE_INFO_ACK,
	MP_ITEM_GUILD_WAREHOUSE_INFO_NACK,

	MP_ITEM_ADDTO_GUILDWARE_NOTIFY,
	MP_ITEM_DELETEFROM_GUILDWARE_NOTIFY,

	MP_ITEM_GUILD_WAREHOUSE_LEAVE,

	MP_ITEM_SHOPITEM_INFO_SYN,
	MP_ITEM_SHOPITEM_INFO_ACK,
	MP_ITEM_SHOPITEM_INFO_NACK,

	MP_ITEM_SHOPITEM_USEDINFO,
	MP_ITEM_SHOPITEM_MPINFO,

	MP_ITEM_SHOPITEM_USE_SYN,
	MP_ITEM_SHOPITEM_USE_ACK,
	MP_ITEM_SHOPITEM_USE_NACK,

	MP_ITEM_SHOPITEM_TIME_UPDATE,
	MP_ITEM_SHOPITEM_USEEND,

	MP_ITEM_SHOPITEM_MSG,
	MP_ITEM_SHOPITEM_ONEMINUTE,
	MP_ITEM_SHOPITEM_MONEYPROTECT,
	MP_ITEM_SHOPITEM_EXPPROTECT,
	MP_ITEM_SHOPITEM_MIXUP,
	MP_ITEM_SHOPITEM_STATEMINUS,	
	
	MP_ITEM_SHOPITEM_UNSEAL_SYN,
	MP_ITEM_SHOPITEM_UNSEAL_ACK,
	MP_ITEM_SHOPITEM_UNSEAL_NACK,

	MP_ITEM_SHOPITEM_CHANGEMAP_SYN,
	MP_ITEM_SHOPITEM_CHANGEMAP_ACK,
	MP_ITEM_SHOPITEM_CHANGEMAP_NACK,

	MP_ITEM_SHOPITEM_SAVEPOINT_ADD_SYN,
	MP_ITEM_SHOPITEM_SAVEPOINT_ADD_ACK,
	MP_ITEM_SHOPITEM_SAVEPOINT_ADD_NACK,
	
	MP_ITEM_SHOPITEM_SAVEPOINT_UPDATE_SYN,
	MP_ITEM_SHOPITEM_SAVEPOINT_UPDATE_ACK,
	MP_ITEM_SHOPITEM_SAVEPOINT_UPDATE_NACK,

	MP_ITEM_SHOPITEM_SAVEPOINT_DEL_SYN,
	MP_ITEM_SHOPITEM_SAVEPOINT_DEL_ACK,
	MP_ITEM_SHOPITEM_SAVEPOINT_DEL_NACK,
	
	MP_ITEM_SHOPITEM_REVIVEOTHER_SYN,
	MP_ITEM_SHOPITEM_REVIVEOTHER_ACK,
	MP_ITEM_SHOPITEM_REVIVEOTHER_NACK,
	
	MP_ITEM_SHOPITEM_AVATAR_USE_SYN,
	MP_ITEM_SHOPITEM_AVATAR_USE_ACK,
	MP_ITEM_SHOPITEM_AVATAR_USE_NACK,
	MP_ITEM_SHOPITEM_AVATAR_PUTON,
	MP_ITEM_SHOPITEM_AVATAR_TAKEOFF,
	MP_ITEM_SHOPITEM_AVATAR_CHANGE,
	MP_ITEM_SHOPITEM_AVATAR_USE,
	MP_ITEM_SHOPITEM_AVATAR_INFO,
	MP_ITEM_SHOPITEM_AVATAR_DISCARD,

	MP_ITEM_SHOPITEM_PET_SUMMON_SYN,
	MP_ITEM_SHOPITEM_PET_SUMMON_ACK,
	MP_ITEM_SHOPITEM_PET_SUMMON_NACK,
	MP_ITEM_SHOPITEM_PET_SEAL_SYN,
	MP_ITEM_SHOPITEM_PET_SEAL_ACK,	
	MP_ITEM_SHOPITEM_PET_SEAL_NACK,
	MP_ITEM_SHOPITEM_PET_USE,	

	MP_ITEM_SHOPITEM_EFFECT,
	MP_ITEM_SHOPITEM_SLOTOVERITEM,
	
	MP_ITEM_EVENTITEM_USE,
	
	MP_ITEM_SHOPITEM_PROTECTALL,

	MP_ITEM_SHOPITEM_CHASEUSE_SYN,
	MP_ITEM_SHOPITEM_CHASEUSE_ACK,
	MP_ITEM_SHOPITEM_CHASEUSE_NACK,
	MP_ITEM_SHOPITEM_CHASE_SYN,
	MP_ITEM_SHOPITEM_CHASE_ACK,
	MP_ITEM_SHOPITEM_CHASE_NACK,
	MP_ITEM_SHOPITEM_CHASE_TRACKING,

	MP_ITEM_SHOPITEM_NCUSE_SYN,
	MP_ITEM_SHOPITEM_NCUSE_ACK,
	MP_ITEM_SHOPITEM_NCUSE_NACK,
	MP_ITEM_SHOPITEM_NCHANGE_SYN,
	MP_ITEM_SHOPITEM_NCHANGE_ACK,
	MP_ITEM_SHOPITEM_NCHANGE_NACK,

	MP_ITEM_REINFORCE_WITHSHOPITEM_SYN,
	MP_ITEM_REINFORCE_WITHSHOPITEM_ACK,
	MP_ITEM_REINFORCE_WITHSHOPITEM_NACK,

	MP_ITEM_SHOPITEM_CHARCHANGE_SYN,
	MP_ITEM_SHOPITEM_CHARCHANGE_ACK,
	MP_ITEM_SHOPITEM_CHARCHANGE_NACK,
	MP_ITEM_SHOPITEM_CHARCHANGE,

	MP_ITEM_SHOPITEM_SEAL_SYN,
	MP_ITEM_SHOPITEM_SEAL_ACK,
	MP_ITEM_SHOPITEM_SEAL_NACK,

	MP_ITEM_MONSTER_RAREOBTAIN_NOTIFY,
	
	MP_ITEM_SHOPITEM_JOBCHANGE_SYN,
	MP_ITEM_SHOPITEM_JOBCHANGE_ACK,
	MP_ITEM_SHOPITEM_JOBCHANGE_NACK,

	MP_ITEM_USE_NOTIFY,

	MP_ITEM_SHOPITEM_REINFORCERESET_SYN,
	MP_ITEM_SHOPITEM_REINFORCERESET_ACK,
	MP_ITEM_SHOPITEM_REINFORCERESET_NACK,

	MP_ITEM_SHOPITEM_RARECREATE_SYN,
	MP_ITEM_SHOPITEM_RARECREATE_ACK,
	MP_ITEM_SHOPITEM_RARECREATE_NACK,

	MP_ITEM_PETINVEN_INFO_SYN,
	MP_ITEM_PETINVEN_INFO_ACK,
	MP_ITEM_PETINVEN_INFO_NACK,

	MP_ITEM_SHOPITEM_SHOUT_SYN,
	MP_ITEM_SHOPITEM_SHOUT_ACK,
	MP_ITEM_SHOPITEM_SHOUT_NACK,
	MP_ITEM_SHOPITEM_SHOUT_SENDSERVER,
	MP_ITEM_SHOPITEM_SHOUT_SENDACK,

	MP_ITEM_CHANGEITEM_NACK,
	MP_ITEM_SHOPITEM_AVATAR_USE_ACKDB,
	MP_ITEM_SHOPITEM_EQUIP_USEINFODB,


	MP_ITEM_QUERY_EQUI_SYN,
	MP_ITEM_QUERY_EQUI_ACK,

	MP_ITEM_STONE_DK_SYN,
	MP_ITEM_STONE_DK_ACK,
    MP_ITEM_STONE_DK_NACK,
	MP_ITEM_STONE_XQ_SYN,
	MP_ITEM_STONE_XQ_ACK,
    MP_ITEM_STONE_XQ_NACK,

	MP_ITEM_FULLINVEN_ALERT,

	MP_ITEM_TPM_SYN,
	MP_ITEM_TPM_SUCCESS_ACK, 
	MP_ITEM_TPM_BIGFAILED_ACK,
	MP_ITEM_TPM_FAILED_ACK, 
	MP_ITEM_TPM_MSG,

	MP_ITEM_TPM_ADDITEM_SYN,
	MP_ITEM_TPM_ADDITEM_ACK,
	MP_ITEM_TPM_ADDITEM_NACK,

	MP_ITEM_TPM_RELEASEITEM,

	MP_ITEM_TITANMIX_SYN,
	MP_ITEM_TITANMIX_ACK,
	MP_ITEM_TITANMIX_ACK_DELETEPARTS,
	MP_ITEM_TITANMIX_NACK,

	MP_ITEM_TITANMIX_ADDITEM_SYN,
	MP_ITEM_TITANMIX_ADDITEM_ACK,
	MP_ITEM_TITANMIX_ADDITEM_NACK,

	MP_ITEM_TITANMIX_RELEASEITEM,

	MP_ITEM_TITANUPGRADE_SYN,
	MP_ITEM_TITANUPGRADE_ACK,
	MP_ITEM_TITANUPGRADE_ACK_DELETEMATERIAL,
	MP_ITEM_TITANUPGRADE_NACK,

	MP_ITEM_TITANUPGRADE_ADDITEM_SYN,
	MP_ITEM_TITANUPGRADE_ADDITEM_ACK,
	MP_ITEM_TITANUPGRADE_ADDITEM_NACK,

	MP_ITEM_TITANUPGRADE_RELEASEITEM,

	MP_ITEM_TITAN_REGISTER_SYN,
	MP_ITEM_TITAN_REGISTER_ACK,
	MP_ITEM_TITAN_REGISTER_NACK,

	MP_ITEM_TITAN_REGISTER_ADDITEM_SYN,
	MP_ITEM_TITAN_REGISTER_ADDITEM_ACK,
	MP_ITEM_TITAN_REGISTER_ADDITEM_NACK,

	MP_ITEM_TITAN_REGISTER_RELEASEITEM,

	MP_ITEM_TITANBREAK_SYN,
	MP_ITEM_TITANBREAK_ACK,
	MP_ITEM_TITANBREAK_ACK_DELETEITEM,
	MP_ITEM_TITANBREAK_NACK,

	MP_ITEM_TITANBREAK_ADDITEM_SYN,
	MP_ITEM_TITANBREAK_ADDITEM_ACK,
	MP_ITEM_TITANBREAK_ADDITEM_NACK,

	MP_ITEM_TITANBREAK_RELEASEITEM,

	MP_ITEM_TITAN_DISSOLUTION_SYN,
	MP_ITEM_TITAN_DISSOLUTION_ACK,
	MP_ITEM_TITAN_DISSOLUTION_NACK,

	MP_ITEM_TITAN_DISSOLUTION_ADDITEM_SYN,
	MP_ITEM_TITAN_DISSOLUTION_ADDITEM_ACK,
	MP_ITEM_TITAN_DISSOLUTION_ADDITEM_NACK,

	MP_ITEM_TITAN_DISSOLUTION_RELEASEITEM,
	
	MP_ITEM_TITAN_DISCARD_EQUIPITEM,

	MP_ITEM_TITAN_EQUIP_REPAIR_SYN,
	MP_ITEM_TITAN_EQUIP_REPAIR_ACK,
	MP_ITEM_TITAN_EQUIP_REPAIR_TOTAL_SYN,
	MP_ITEM_TITAN_EQUIP_REPAIR_TOTAL_ACK,
	MP_ITEM_TITAN_EQUIP_REPAIR_NACK,

	MP_ITEM_TITAN_APPEARANCE_CHANGE,
	MP_ITEM_PROTOCOL_MAX = 254,
};


enum MP_PROTOCOL_ITEMEXT
{
	MP_ITEMEXT_SHOPITEM_CURSE_CANCELLATION_ADDITEM_SYN,
	MP_ITEMEXT_SHOPITEM_CURSE_CANCELLATION_ADDITEM_ACK,
	MP_ITEMEXT_SHOPITEM_CURSE_CANCELLATION_ADDITEM_NACK,

	MP_ITEMEXT_SHOPITEM_CURSE_CANCELLATION_RELEASE,
	MP_ITEMEXT_SHOPITEM_CURSE_CANCELLATION_DELETEITEM,

	MP_ITEMEXT_SHOPITEM_CURSE_CANCELLATION_SYN,
	MP_ITEMEXT_SHOPITEM_CURSE_CANCELLATION_ACK,
	MP_ITEMEXT_SHOPITEM_CURSE_CANCELLATION_NACK,

	MP_ITEMEXT_UNIQUEITEM_MIX_ADDITEM_SYN,
	MP_ITEMEXT_UNIQUEITEM_MIX_ADDITEM_ACK,
	MP_ITEMEXT_UNIQUEITEM_MIX_ADDITEM_NACK,

	MP_ITEMEXT_UNIQUEITEM_MIX_RELEASE,
	MP_ITEMEXT_UNIQUEITEM_MIX_DELETEITEM,

	MP_ITEMEXT_UNIQUEITEM_MIX_SYN,
	MP_ITEMEXT_UNIQUEITEM_MIX_ACK,
	MP_ITEMEXT_UNIQUEITEM_MIX_NACK,

    MP_ITEMEXT_SHOPITEM_DECORATION_ON,

	MP_ITEMEXT_SKINITEM_SELECT_SYN,
	MP_ITEMEXT_SKINITEM_SELECT_ACK,
	MP_ITEMEXT_SKINITEM_SELECT_NACK,
	MP_ITEMEXT_SKINITEM_DISCARD_ACK,
	//[右键删除buff协议][By:十里坡剑神][QQ:112582793][2017/11/22]
	MP_ITEM_BUF_DEL_SYN,  
	//[快速加点协议][By:十里坡剑神][QQ:112582793][2017/12/5]
	MP_ITEM_ADDPOINT_SYN,
	MP_ITEM_ADDPOINT_ACK,
	MP_ITEM_ADDPOINT_NACK,
	//[在线充值元宝刷新][By:十里坡剑神][QQ:112582793][2017/11/22]
	MP_ITEM_GOLD_MONEY_SYN,	
	//[耐久，制造者附加][By:十里坡剑神][QQ:112582793][2018/1/2]
	MP_ITEM_ABRASION_ACK,
	MP_ITEM_MAKER_ACK,
	//[元宝物品使用协议][By:十里坡剑神][QQ:112582793][2018/2/2]
	MP_ITEM_GOLDITEMUSE_SYN,
	MP_ITEM_GOLDITEMUSE_ACK,
	MP_ITEM_GOLDITEMUSE_NACK,
	//[超级狮子吼][By:十里坡剑神][QQ:112582793][2018/2/19]
	MP_ITEM_SHOPITEM_SUPERSHOUT_SYN,
	MP_ITEM_SHOPITEM_SUPERSHOUT_ACK,
	MP_ITEM_SHOPITEM_SUPERSHOUT_SENDSERVER,
	//[发送物品信息查询][By:十里坡剑神][QQ:112582793][2018/4/3]
	MP_ITEM_SENDINFO_SYN,
	MP_ITEM_SENDINFO_ACK,
	MP_ITEM_SENDINFO_NACK,
	//[牛巨任务物品使用协议][By:十里坡剑神][QQ:112582793][2018/4/3]
	MP_ITEMEX_NJQUEST_SYN,
	MP_ITEMEX_NJQUEST_ACK,
	MP_ITEMEX_NJQUEST_NACK,
	//[背包整理协议][By:十里坡剑神][QQ:112582793][2018/6/11]
	MP_ITEMEX_PAKMOVE_SYN,
	MP_ITEMEX_PAKMOVE_ACK,
	MP_ITEMEX_PAKMOVE_NACK,
	//[物品锁定][By:十里坡剑神][QQ:112582793][2018/6/17]
	MP_ITEMEX_LOCK_SYN,
	//[商城在线更新][By:十里坡剑神][QQ:112582793][2018/6/17]
	MP_ITEMEX_UPDATE_GOLDSHOP_SYN,
	MP_ITEMEX_UPDATE_GOLDSHOP_BEGIN,
	MP_ITEMEX_UPDATE_GOLDSHOP_ING,
	MP_ITEMEX_UPDATE_GOLDSHOP_END,
};


enum MP_PROTOCOL_AUCTIONBOARD
{
	MP_AUCTIONBOARD_OPEN_SYN,
	MP_AUCTIONBOARD_OPEN_ACK,
	MP_AUCTIONBOARD_OPEN_NACK,

	MP_AUCTIONBOARD_LIST_SYN,	
	MP_AUCTIONBOARD_LIST_ACK,	
	MP_AUCTIONBOARD_LIST_NACK,

	MP_AUCTIONBOARD_CONTENTS_SYN,
	MP_AUCTIONBOARD_CONTENTS_ACK,	
	MP_AUCTIONBOARD_CONTENTS_NACK,

	MP_AUCTIONBOARD_WRITE_SYN,		
	MP_AUCTIONBOARD_WRITE_ACK,	
	MP_AUCTIONBOARD_WRITE_NACK,

	MP_AUCTIONBOARD_DELETE_SYN,	
	MP_AUCTIONBOARD_DELETE_ACK,
	MP_AUCTIONBOARD_DELETE_NACK,
	
	MP_AUCTIONBOARD_BID_SYN,
	MP_AUCTIONBOARD_BID_ACK,
	MP_AUCTIONBOARD_BID_NACK,

	MP_AUCTIONBOARD_CLOSECONTENTS,	
};

enum MP_PROTOCOL_CHEAT
{
	MP_CHEAT_MOVE_SYN,
	MP_CHEAT_MOVE_ACK,
	MP_CHEAT_MOVE_NACK,

	MP_CHEAT_CHANGEMAP_SYN,
	MP_CHEAT_CHANGEMAP_ACK,
	MP_CHEAT_CHANGEMAP_NACK,

	MP_CHEAT_LIFE_SYN,
	MP_CHEAT_LIFE_ACK,
	MP_CHEAT_LIFE_NACK,

	MP_CHEAT_MP_SYN,
	MP_CHEAT_MP_ACK,
	MP_CHEAT_MP_NACK,

	MP_CHEAT_ITEM_SYN,
	MP_CHEAT_ITEM_ACK,
	MP_CHEAT_ITEM_NACK,
	
	MP_CHEAT_MANA_SYN, 
	MP_CHEAT_MANA_ACK, 
	MP_CHEAT_MANA_NACK, 
	
	MP_CHEAT_MUGONGSUNG_SYN,
	MP_CHEAT_MUGONGSUNG_ACK,
	MP_CHEAT_MUGONGSUNG_NACK,

	MP_CHEAT_MONEY_SYN,
	MP_CHEAT_MONEY_ACK,
	MP_CHEAT_MONEY_NACK,

	MP_CHEAT_RELOADING,

	MP_CHEAT_LEVELUP_SYN,
	MP_CHEAT_LEVELUP_ACK,
	MP_CHEAT_LEVELUP_NACK,

	MP_CHEAT_ABILITYEXP_SYN,
	
	MP_CHEAT_MOVETOCHAR_SYN,
	MP_CHEAT_MOVETOCHAR_ACK,
	MP_CHEAT_MOVETOCHAR_NACK,

	MP_CHEAT_WHEREIS_SYN,
	MP_CHEAT_WHEREIS_ACK,
	MP_CHEAT_WHEREIS_NACK,

	MP_CHEAT_BANCHARACTER_SYN,	//client(gm) -> map; map -> agent
	MP_CHEAT_BANCHARACTER_ACK,	//agent -> client(gm)
	MP_CHEAT_BANCHARACTER_NACK,	//agent or map ->client(gm)

	MP_CHEAT_BLOCKCHARACTER_SYN,	//client(gm) -> map; map -> agent
	MP_CHEAT_BLOCKCHARACTER_ACK,	//agent -> client(gm)
	MP_CHEAT_BLOCKCHARACTER_NACK,	//agent or map ->client(gm)

	MP_CHEAT_GETID_SYN,
	MP_CHEAT_GETID_ACK,
	MP_CHEAT_GETID_NACK,	
	
	MP_CHEAT_PKALLOW_SYN,
	MP_CHEAT_PKALLOW_ACK,
	MP_CHEAT_PKALLOW_NACK,

	MP_CHEAT_MOVEUSER_SYN,
	MP_CHEAT_MOVEUSER_ACK,
	MP_CHEAT_MOVEUSER_NACK,

	MP_CHEAT_HIDE_SYN,
	MP_CHEAT_HIDE_ACK,
	MP_CHEAT_HIDE_NACK,
	
	MP_CHEAT_CHECKIP_SYN,
	MP_CHEAT_CHECKIP_ACK,
	MP_CHEAT_CHECKIP_NACK,
	
	MP_CHEAT_WHEREIS_MAPSERVER_ACK,
	
	MP_CHEAT_EVENT_MONSTER_REGEN,
	MP_CHEAT_EVENT_MONSTER_DELETE,

	MP_CHEAT_ADDMUGONG_SYN,
	MP_CHEAT_ADDMUGONG_ACK,
	MP_CHEAT_ADDMUGONG_NACK,
	
	MP_CHEAT_BANMAP_SYN,
	MP_CHEAT_BANMAP_ACK,
	MP_CHEAT_BANMAP_NACK,
	
	MP_CHEAT_GENGOL_SYN,
	MP_CHEAT_GENGOL_ACK,
	MP_CHEAT_GENGOL_NACK,

	MP_CHEAT_MINCHUB_SYN,
	MP_CHEAT_MINCHUB_ACK,
	MP_CHEAT_MINCHUB_NACK,

	MP_CHEAT_CHERYUK_SYN,
	MP_CHEAT_CHERYUK_ACK,
	MP_CHEAT_CHERYUK_NACK,
	
	MP_CHEATE_SIMMEK_SYN,
	MP_CHEATE_SIMMEK_ACK,
	MP_CHEATE_SIMMEK_NACK,
	
	MP_CHEAT_AGENTCHECK_SYN,
	MP_CHEAT_AGENTCHECK_ACK,
	MP_CHEAT_AGENTCHECK_NACK,
	
	MP_CHEAT_GM_LOGIN_SYN,
	MP_CHEAT_GM_LOGIN_ACK,
	MP_CHEAT_GM_LOGIN_NACK,

	MP_CHEAT_KILL_ALLMONSTER_SYN,
	MP_CHEAT_KILL_ALLMONSTER_ACK,
	MP_CHEAT_KILL_ALLMONSTER_NACK,
	
	MP_CHEAT_PARTYINFO_SYN,
	MP_CHEAT_PARTYINFO_ACK,
	MP_CHEAT_PARTYINFO_NACK,
	
	MP_CHEAT_NOTICE_SYN,

	MP_CHEAT_EVENT_SYN,	
	
	MP_CHEAT_MUNPADATECLR_SYN,
	
	MP_CHEAT_CHANGE_EVENTMAP_SYN,
	MP_CHEAT_CHANGE_EVENTMAP_ACK,
	MP_CHEAT_CHANGE_EVENTMAP_NACK,
	MP_CHEAT_EVENT_START_SYN,
	MP_CHEAT_EVENT_READY_SYN,
	MP_CHEAT_EVENTMAP_RESULT,
	
	MP_CHEAT_EVENTNOTIFY_ON,
	MP_CHEAT_EVENTNOTIFY_OFF,

	MP_CHEAT_GETSHOPITEM,

	MP_CHEAT_ADDTIME,

	MP_CHEAT_STAGE_SYN,
	MP_CHEAT_STAGE_ACK,
	MP_CHEAT_BOSSMOB_SYN,
	
	MP_CHEAT_PLUSTIME_ALLOFF,
	MP_CHEAT_PLUSTIME_ON,
	MP_CHEAT_PLUSTIME_OFF,

	MP_CHEAT_JACKPOT_GETPRIZE,
	MP_CHEAT_JACKPOT_ONOFF,
	MP_CHEAT_JACKPOT_MONEYPERMONSTER,
	MP_CHEAT_JACKPOT_PROBABILITY,
	MP_CHEAT_JACKPOT_CONTROL,
	
	MP_CHEAT_GUILDUNION_CLEAR,
	MP_CHEAT_CHANGE_MAINATTR_SYN,
	MP_CHEAT_CHANGE_MAINATTR_ACK,
	MP_CHEAT_CHANGE_MAINATTR_NACK,
	MP_CHEAT_CHANGE_SUBATTR_SYN,
	MP_CHEAT_CHANGE_SUBATTR_ACK,
	MP_CHEAT_CHANGE_SUBATTR_NACK,
	
	MP_CHEAT_MOB_CHAT,

	MP_CHEAT_ITEM_OPTION_SYN,

	MP_CHEAT_MUSSANG_READY,

	MP_CHEAT_PET_GRADE,
	MP_CHEAT_PET_STAMINA,
	MP_CHEAT_PET_FRIENDSHIP_SYN,
	MP_CHEAT_PET_FRIENDSHIP_ACK,
	MP_CHEAT_PET_FRIENDSHIP_NACK,
	MP_CHEAT_PET_SKILLREADY_SYN,
	MP_CHEAT_PET_SKILLREADY_ACK,

	MP_CHEAT_PET_SELECTED_FRIENDSHIP_SYN,
	MP_CHEAT_PET_SELECTED_FRIENDSHIP_ACK,
	MP_CHEAT_PET_SELECTED_FRIENDSHIP_NACK,

	MP_CHEAT_NPCHIDE_SYN,
	MP_CHEAT_NPCHIDE_ACK,
	MP_CHEAT_NPCHIDE_NACK,

	MP_CHEAT_GUILDPOINT_SYN,
	MP_CHEAT_GUILDPOINT_ACK,
	MP_CHEAT_GUILDPOINT_NACK,

	MP_CHEAT_GUILDHUNTED_MONSTERCOUNT_SYN,
	MP_CHEAT_GUILDHUNTED_MONSTERCOUNT_ACK,
	MP_CHEAT_GUILDHUNTED_MONSTERCOUNT_NACK,

	MP_CHEAT_DAMAGE_SYN,
	MP_CHEAT_DAMAGE_ACK,
	MP_CHEAT_DAMAGE_NACK,

	MP_CHEAT_MAP_CONDITION,
	MP_CHEAT_AGENT_CONDITION,

	MP_CHEAT_TITAN_FUEL_SPELL_MAX_SYN,

	MP_CHEAT_BOBUSANGINFO_REQUEST_SYN,
	MP_CHEAT_BOBUSANGINFO_REQUEST_ACK,
	MP_CHEAT_BOBUSANGINFO_REQUEST_NACK,
	
	MP_CHEAT_BOBUSANG_LEAVE_SYN,
	MP_CHEAT_BOBUSANG_LEAVE_ACK,
	MP_CHEAT_BOBUSANG_LEAVE_NACK,
	
	MP_CHEAT_BOBUSANGINFO_CHANGE_SYN,
	MP_CHEAT_BOBUSANGINFO_CHANGE_ACK,
	MP_CHEAT_BOBUSANGINFO_CHANGE_NACK,

	MP_CHEAT_BOBUSANG_ONOFF_SYN,
	MP_CHEAT_BOBUSANG_ONOFF_ACK,
	MP_CHEAT_BOBUSANG_ONOFF_NACK,

	MP_CHEAT_ITEMLIMIT_SYN,
	MP_CHEAT_ITEMLIMIT_ACK,
	MP_CHEAT_ITEMLIMIT_NACK,

	MP_CHEAT_AUTONOTE_SETTING_SYN,
	MP_CHEAT_AUTONOTE_SETTING_ACK,
	MP_CHEAT_AUTONOTE_SETTING_NACK,

	//GM工具游戏配置修改协议	by:十里坡剑神	QQ:112582793
	MP_CHEAT_GAMECFG_GET_SYN,
	MP_CHEAT_GAMECFG_GET_ACK,
	MP_CHEAT_GAMECFG_SEND_SYN,

	MP_CHEAT_GMGETGOLD_SYN,
	MP_CHEAT_GMGETMALL_SYN,
	MP_CHEAT_GMGETFAME_SYN,
};

enum MP_PROTOCOL_QUICK
{
	MP_QUICK_ADD_SYN,
	MP_QUICK_ADD_ACK,
	MP_QUICK_ADD_NACK,

	MP_QUICK_MOVE_SYN,
	MP_QUICK_MOVE_ACK,
	MP_QUICK_MOVE_NACK,

	MP_QUICK_REM_SYN,
	MP_QUICK_REM_ACK,
	MP_QUICK_REM_NACK,

	MP_QUICK_SET_SYN,
	MP_QUICK_SET_ACK,
	MP_QUICK_SET_NACK,
};

enum MP_PROTOCOL_PACKEDDATA
{
	MP_PACKEDDATA_NORMAL,
	
	MP_PACKEDDATA_TOMAPSERVER,
	MP_PACKEDDATA_TOBROADMAPSERVER,
};

enum MP_PROTOCOL_PARTY
{
	MP_PARTY_INFO,

	MP_PARTY_CREATE_SYN,
	MP_PARTY_CREATE_ACK, 
	MP_PARTY_CREATE_NACK,

	MP_PARTY_ADD_SYN,
	MP_PARTY_ADD_ACK,
	MP_PARTY_ADD_NACK,

	MP_PARTY_ADD_INVITE,

	MP_PARTY_INVITE_ACCEPT_SYN,
	MP_PARTY_INVITE_ACCEPT_ACK,
	MP_PARTY_INVITE_ACCEPT_NACK,

	MP_PARTY_INVITE_DENY_SYN, 
	MP_PARTY_INVITE_DENY_ACK,
	MP_PARTY_INVITE_DENY_NACK,
	
	MP_PARTY_NOTIFYADD_TO_MAPSERVER,
	MP_PARTY_DEL_SYN,
	MP_PARTY_DEL_ACK,
	MP_PARTY_DEL_NACK, 
	MP_PARTY_NOTIFYDELETE_TO_MAPSERVER,
	MP_PARTY_SYNDELETE_TO_MAPSERVER,

	MP_PARTY_BAN_SYN,
	MP_PARTY_BAN_ACK,
	MP_PARTY_BAN_NACK,
	MP_PARTY_NOTIFYBAN_TO_MAPSERVER,

	MP_PARTY_CHANGEMASTER_SYN, 
	MP_PARTY_CHANGEMASTER_ACK,
	MP_PARTY_CHANGEMASTER_NACK,
	MP_PARTY_NOTIFYCHANGEMASTER_TO_MAPSERVER,

	MP_PARTY_BREAKUP_SYN,
	MP_PARTY_BREAKUP_ACK,
	MP_PARTY_BREAKUP_NACK,
	MP_PARTY_NOTIFYBREAKUP_TO_MAPSERVER,

	MP_PARTY_MEMBER_LOGIN,
	MP_PARTY_NOTIFYMEMBER_LOGIN_TO_MAPSERVER,
	MP_PARTY_MEMBER_LOGOUT,
	MP_PARTY_NOTIFYMEMBER_LOGOUT_TO_MAPSERVER,
		
	MP_PARTY_MEMBERLIFE,
	MP_PARTY_MEMBERSHIELD,
	MP_PARTY_MEMBERNAERYUK,	
	MP_PARTY_MEMBERLEVEL,
	MP_PARTY_SENDPOS,
	MP_PARTY_REVIVEPOS,

	MP_PARTY_NOTIFYCHANGES_TO_MAPSERVER,		

	MP_PARTY_CLEAR,			
	
	MP_PARTY_NOTIFYCREATE_TO_MAPSERVER,
	
	MP_PARTY_MEMBER_LOGINMSG,
	MP_PARTY_NOTIFYMEMBER_LOGINMSG,
	
	MP_PARTY_NOTIFYMEMBER_LEVEL,

	MP_PARTY_MONSTER_OBTAIN_NOTIFY,
	MP_PARTY_OBTAIN_MONEY_TO_PARTY,

	MP_PARTY_ERROR,
	MP_PARTY_MASTERTOREQUEST_SYN,
	MP_PARTY_MASTERTOREQUEST_ACK,	
	MP_PARTY_REQUEST_CONSENT_SYN,
	MP_PARTY_REQUEST_CONSENT_ACK,
	MP_PARTY_REQUEST_CONSENT_NACK,
	MP_PARTY_REQUEST_REFUSAL_SYN,
	MP_PARTY_REQUEST_REFUSAL_ACK,
	MP_PARTY_REQUEST_REFUSAL_NACK,
	MP_PARTY_NOTIFY_INFO,
	MP_PARTY_MATCHING_INFO,
	//[小队语音协议][By:十里坡剑神][QQ:112582793][2019/3/20][13:36:48]
	MP_PARTY_VOICE_ADD,
	MP_PARTY_VOICE_QUIT,
};

enum MP_PROTOCOL_PEACEWARMODE
{
	MP_PEACEWARMODE_PEACE,
	MP_PEACEWARMODE_WAR,
};

enum MP_PROTOCOL_UNGIJOSIK
{
	MP_UNGIJOSIK_START,
	MP_UNGIJOSIK_END,
};

enum MP_PROTOCOL_SIGNAL
{
	MP_SIGNAL_COMMONUSER,
	MP_SIGNAL_ONEUSER,
	MP_SIGNAL_SYSTEM,

	MP_SIGNAL_BATTLE,
	MP_SIGNAL_VIMU_RESULT,
};

enum MP_PROTOCOL_TACTIC
{
	MP_TACTIC_START_SYN,
	MP_TACTIC_START_ACK,
	MP_TACTIC_START_NACK,
	
	MP_TACTIC_JOIN_SYN,
	MP_TACTIC_JOIN_ACK,
	MP_TACTIC_JOIN_NACK,
	

	MP_TACTIC_OBJECT_ADD,

	MP_TACTIC_FAIL,
	MP_TACTIC_EXECUTE,
};

enum MP_PROTOCOL_SKILL
{
	MP_SKILL_START_SYN,
	MP_SKILL_START_ACK,
	MP_SKILL_START_NACK,

	MP_SKILL_SKILLOBJECT_ADD,
	MP_SKILL_SKILLOBJECT_REMOVE,
	
	MP_SKILL_ADDOBJECT_TO_SKILLOBJECTAREA_SYN,
	MP_SKILL_ADDOBJECT_TO_SKILLOBJECTAREA_ACK,
	MP_SKILL_ADDOBJECT_TO_SKILLOBJECTAREA_NACK,

	MP_SKILL_REMOVEOBJECT_FROM_SKILLOBJECTAREA_SYN,
	MP_SKILL_REMOVEOBJECT_FROM_SKILLOBJECTAREA_ACK,
	MP_SKILL_REMOVEOBJECT_FROM_SKILLOBJECTAREA_NACK,

	MP_SKILL_SKILL_SINGLE_RESULT,
	
	MP_SKILL_STARTEFFECT,
	
	MP_SKILL_OPERATE_SYN,
	MP_SKILL_OPERATE_ACK,
	MP_SKILL_OPERATE_NACK,
	
	MP_SKILL_DELAY_DAMAGED_TARGETLIST,
	
	MP_SKILL_DELAY_NOTIFY,
	MP_SKILL_JOB_NACK,
};

enum MP_PROTOCOL_MUNPA
{
	MP_MUNPA_LOAD_MUNPALIST_SYN,
	MP_MUNPA_LOAD_MUNPALIST_ACK,
	MP_MUNPA_LOAD_MUNPALIST_NACK,
	
	MP_MUNPA_MUNPAHOME_SYN,
	MP_MUNPA_MUNPAHOME_ACK,
	MP_MUNPA_MUNPAHOME_NACK,
	

	MP_MUNPA_SEARCHMUNPA_SYN,
	MP_MUNPA_SEARCHMUNPA_ACK,
	MP_MUNPA_SEARCHMUNPA_NACK,

	MP_MUNPA_ADDMEMBER_SYN,
	MP_MUNPA_ADDMEMBER_ACK,
	MP_MUNPA_ADDMEMBER_NACK,
	MP_MUNPA_NOTIFY_ADDMEMBER_TO_MAPSERVER,
	MP_MUNPA_MARK_CHANGE,

	MP_MUNPA_DENYMEMBER_SYN, 
	MP_MUNPA_DENYMEMBER_ACK,
	MP_MUNPA_DENYMEMBER_NACK,
	MP_MUNPA_NOTIFY_DENYMEMBER_TO_MAPSERVER,

	MP_MUNPA_CREATE_SYN,	
	MP_MUNPA_CREATE_ACK, 
	MP_MUNPA_CREATE_NACK,
	
	MP_MUNPA_BREAKUP_SYN,	
	MP_MUNPA_BREAKUP_ACK, 
	MP_MUNPA_BREAKUP_NACK,
	
	MP_MUNPA_JOINMEMBERS_INFO_SYN,
	MP_MUNPA_JOINMEMBERS_INFO_ACK,
	MP_MUNPA_JOINMEMBERS_INFO_NACK,
	
	MP_MUNPA_REGULARMEMBERS_INFO_SYN,
	MP_MUNPA_REGULARMEMBERS_INFO_ACK,
	MP_MUNPA_REGULARMEMBERS_INFO_NACK,
	
	MP_MUNPA_BOARD_INFO_SYN,
	MP_MUNPA_BOARD_INFO_ACK,
	MP_MUNPA_BOARD_INFO_NACK,
	
	MP_MUNPA_CHANGERANK_SYN,
	MP_MUNPA_CHANGERANK_ACK, 
	MP_MUNPA_CHANGERANK_NACK,
	MP_MUNPA_NOTIFY_CHANGERANK_TO_MAPSERVER,

	MP_MUNPA_BAN_SYN,
	MP_MUNPA_BAN_ACK,
	MP_MUNPA_BAN_NACK,
	MP_MUNPA_NOTIFYBAN_TO_MAPSERVER, 
	

	MP_MUNPA_CREATEBOARD_SYN,
	MP_MUNPA_CREATEBOARD_ACK,
	MP_MUNPA_CREATEBOARD_NACK,
	
	MP_MUNPA_DELETEBOARD_SYN,
	MP_MUNPA_DELETEBOARD_ACK,
	MP_MUNPA_DELETEBOARD_NACK,

	MP_MUNPA_BOARDRANK_INFO_SYN,
	MP_MUNPA_BOARDRANK_INFO_ACK,
	MP_MUNPA_BOARDRANK_INFO_NACK,
	
	MP_MUNPA_BOARD_MODIFYRANK_INFO_SYN,
	MP_MUNPA_BOARD_MODIFYRANK_INFO_ACK,
	MP_MUNPA_BOARD_MODIFYANK_INFO_NACK, 
	
	MP_MUNPA_APPLCATEINFO_SYN,
	MP_MUNPA_APPLCATEINFO_ACK,
	MP_MUNPA_APPLCATEINFO_NACK,

	MP_MUNPA_JOINMEMBER_SYN, 
	MP_MUNPA_JOINMEMBER_ACK,
	MP_MUNPA_JOINMEMBER_NACK,

	MP_MUNPA_JOINMEMBERCANCEL_SYN,
	MP_MUNPA_JOINMEMBERCANCEL_ACK,
	MP_MUNPA_JOINMEMBERCANCEL_NACK,
	
	MP_MUNPA_SECEDE_SYN,
	MP_MUNPA_SECEDE_ACK,
	MP_MUNPA_SECEDE_NACK,
	
	MP_MUNPA_BOARD_SUBJECTLIST_SYN,
	MP_MUNPA_BOARD_SUBJECTLIST_ACK,
	MP_MUNPA_BOARD_SUBJECTLIST_NACK,

	MP_MUNPA_BOARD_CONTENTS_SYN,
	MP_MUNPA_BOARD_CONTENTS_ACK,
	MP_MUNPA_BOARD_CONTENTS_NACK,

	MP_MUNPA_BOARD_WRITE_SYN, 
	MP_MUNPA_BOARD_WRITE_ACK,
	MP_MUNPA_BOARD_WRITE_NACK,

	MP_MUNPA_BOARD_MODIFY_SYN, 
	MP_MUNPA_BOARD_MODIFY_ACK,
	MP_MUNPA_BOARD_MODIFY_NACK,
	
	MP_MUNPA_BOARD_DELETE_SYN, 
	MP_MUNPA_BOARD_DELETE_ACK,
	MP_MUNPA_BOARD_DELETE_NACK,

	MP_MUNPA_BOARD_REPLY_SYN,
	MP_MUNPA_BOARD_REPLY_ACK,
	MP_MUNPA_BOARD_REPLY_NACK,

	MP_MUNPA_NOT_INLOCATION_NACK,
	MP_MUNPA_NOTIFYBREAKUP_TO_MAPSERVER,
	
	MP_MUNPA_MODIFY_INTROMSG_SYN,
	MP_MUNPA_MODIFY_INTROMSG_ACK,
	MP_MUNPA_MODIFY_INTROMSG_NACK,
	
	MP_MUNPA_LEAVE_WAREHOUSE,

	MP_MUNPA_PUTIN_MONEY_SYN,
	MP_MUNPA_PUTIN_MONEY_ACK,
	MP_MUNPA_PUTIN_MONEY_NACK,

	MP_MUNPA_PUTOUT_MONEY_SYN,
	MP_MUNPA_PUTOUT_MONEY_ACK,
	MP_MUNPA_PUTOUT_MONEY_NACK,
	
	MP_MUNPA_DENYMEMBER_TO_TARGET_ACK,
	MP_MUNPA_BAN_TO_TARGET_ACK,
	MP_MUNPA_CHANGERANK_TO_TARGET_ACK,
	MP_MUNPA_ACCMEMBER_TO_TARGET_ACK,

};

enum MP_PROTOCOL_PYOGUK
{
	MP_PYOGUK_LISTINFO_SYN,
	MP_PYOGUK_LISTINFO_ACK,
	MP_PYOGUK_LISTINFO_NACK,
	MP_PYOGUK_BUY_SYN,
	MP_PYOGUK_BUY_ACK,
	MP_PYOGUK_BUY_NACK,
	
	MP_PYOGUK_DEL_SYN,
	MP_PYOGUK_DEL_ACK,
	MP_PYOGUK_DEL_NACK,
	
	MP_PYOGUK_PUTIN_MONEY_SYN,
	MP_PYOGUK_PUTIN_MONEY_ACK,
	MP_PYOGUK_PUTIN_MONEY_NACK,

	MP_PYOGUK_PUTOUT_MONEY_SYN,
	MP_PYOGUK_PUTOUT_MONEY_ACK,
	MP_PYOGUK_PUTOUT_MONEY_NACK,

	MP_PYOGUK_INFO,
};

enum MP_PROTOCOL_KYUNGGONG
{
	MP_KYUNGGONG_CHANGE_NOTIFY,
	MP_KYUNGGONG_ABILITY_CHANGE_NOTIFY,
};

enum MP_PROTOCOL_SIMBUB
{
	MP_SIMBUB_CHANGE_SYN,
	MP_SIMBUB_CHANGE_ACK,
	MP_SIMBUB_CHANGE_NACK,
};

enum MP_PROTOCOL_EXCHANGE
{
	MP_EXCHANGE_APPLY,		
	MP_EXCHANGE_APPLY_SYN,	
	MP_EXCHANGE_APPLY_ACK,
	MP_EXCHANGE_APPLY_NACK,

	MP_EXCHANGE_ACCEPT,			
	MP_EXCHANGE_ACCEPT_SYN,
	MP_EXCHANGE_ACCEPT_ACK,
	MP_EXCHANGE_ACCEPT_NACK,

	MP_EXCHANGE_CANTAPPLY,

	MP_EXCHANGE_REJECT,				
	MP_EXCHANGE_REJECT_SYN,			

	MP_EXCHANGE_WAITING_CANCEL,
	MP_EXCHANGE_WAITING_CANCEL_SYN,
	MP_EXCHANGE_WAITING_CANCEL_ACK,
	MP_EXCHANGE_WAITING_CANCEL_NACK,

	MP_EXCHANGE_START,			

	MP_EXCHANGE_ADDITEM,	
	MP_EXCHANGE_ADDITEM_SYN,
	MP_EXCHANGE_ADDITEM_ACK,
	MP_EXCHANGE_ADDITEM_NACK,

	MP_EXCHANGE_DELITEM,		
	MP_EXCHANGE_DELITEM_SYN,	
	MP_EXCHANGE_DELITEM_ACK,
	MP_EXCHANGE_DELITEM_NACK,

	MP_EXCHANGE_INPUTMONEY,		
	MP_EXCHANGE_INPUTMONEY_SYN,
	MP_EXCHANGE_INPUTMONEY_ACK,
	MP_EXCHANGE_INPUTMONEY_NACK,

	MP_EXCHANGE_INPUTGOLD,	
	MP_EXCHANGE_INPUTGOLD_SYN,
	MP_EXCHANGE_INPUTGOLD_ACK,
	MP_EXCHANGE_INPUTGOLD_NACK,
	
	MP_EXCHANGE_LOCK,			
	MP_EXCHANGE_LOCK_SYN,	
	MP_EXCHANGE_LOCK_ACK,
	MP_EXCHANGE_LOCK_NACK,

	MP_EXCHANGE_UNLOCK,		
	MP_EXCHANGE_UNLOCK_SYN,	
	MP_EXCHANGE_UNLOCK_ACK,
	MP_EXCHANGE_UNLOCK_NACK,

	MP_EXCHANGE_EXCHANGE,		
	MP_EXCHANGE_EXCHANGE_SYN,	
	MP_EXCHANGE_EXCHANGE_ACK,
	MP_EXCHANGE_EXCHANGE_NACK,

	MP_EXCHANGE_CANCEL,			
	MP_EXCHANGE_CANCEL_SYN,	
	MP_EXCHANGE_CANCEL_ACK,
	MP_EXCHANGE_CANCEL_NACK,

	MP_EXCHANGE_INSERT,
	MP_EXCHANGE_REMOVE,
	MP_EXCHANGE_SETMONEY,
};

enum MP_PROTOCOL_STREESTALL
{
	MP_STREETSTALL_START,
	MP_STREETSTALL_END,

	MP_STREETSTALL_OPEN_SYN,
	MP_STREETSTALL_OPEN_ACK,
	MP_STREETSTALL_OPEN_NACK,

	MP_STREETSTALL_CLOSE_SYN, 
	MP_STREETSTALL_CLOSE_ACK,
	MP_STREETSTALL_CLOSE_NACK,
	MP_STREETSTALL_CLOSE,

	MP_STREETSTALL_LOCKITEM_SYN,
	MP_STREETSTALL_LOCKITEM_ACK,
	MP_STREETSTALL_LOCKITEM_NACK,
	MP_STREETSTALL_LOCKITEM,
	
	MP_STREETSTALL_UNLOCKITEM_SYN,
	MP_STREETSTALL_UNLOCKITEM_ACK,
	MP_STREETSTALL_UNLOCKITEM_NACK,
	MP_STREETSTALL_UNLOCKITEM,

	MP_STREETSTALL_DELETEITEM_SYN,
	MP_STREETSTALL_DELETEITEM_ACK,
	MP_STREETSTALL_DELETEITEM_NACK,
	MP_STREETSTALL_DELETEITEM,

	MP_STREETSTALL_BUYITEM,
	MP_STREETSTALL_BUYITEM_ERROR,
	MP_STREETSTALL_BUYITEM_SYN,	
	MP_STREETSTALL_BUYITEM_ACK,
	MP_STREETSTALL_BUYITEM_NACK,
	MP_STREETSTALL_SELLITEM,
	MP_STREETSTALL_SELLITEM_ERROR,
	MP_STREETSTALL_SELLITEM_SYN,		
	MP_STREETSTALL_SELLITEM_ACK,
	MP_STREETSTALL_SELLITEM_NACK,


	MP_STREETSTALL_GUESTIN_SYN,
	MP_STREETSTALL_GUESTIN_ACK,
	MP_STREETSTALL_GUESTIN_NACK,

	MP_STREETSTALL_GUESTOUT_SYN,
	MP_STREETSTALL_GUESTOUT_ACK,
	MP_STREETSTALL_GUESTOUT_NACK,
	
	MP_STREETSTALL_EDITTITLE_SYN,
	MP_STREETSTALL_EDITTITLE_ACK,
	MP_STREETSTALL_EDITTITLE_NACK,
	MP_STREETSTALL_EDITTITLE,
	
	MP_STREETSTALL_UPDATEITEM,
	MP_STREETSTALL_UPDATE_SYN,
	MP_STREETSTALL_UPDATE_ACK,
	MP_STREETSTALL_UPDATE_NACK,
	MP_STREETSTALL_UPDATE,
	MP_STREETSTALL_UPDATEEND_SYN,
	MP_STREETSTALL_UPDATEEND_ACK,
	MP_STREETSTALL_UPDATEEND_NACK,
	MP_STREETSTALL_UPDATEEND,
	
	MP_STREETSTALL_FAKEREGISTITEM_SYN,			
	MP_STREETSTALL_FAKEREGISTITEM_ACK,
	MP_STREETSTALL_FAKEREGISTITEM_NACK,
	MP_STREETSTALL_FAKEREGISTITEM,

	MP_STREETSTALL_FAKEREGISTBUYITEM_SYN,			
	MP_STREETSTALL_FAKEREGISTBUYITEM_ACK,
	MP_STREETSTALL_FAKEREGISTBUYITEM_NACK,
	MP_STREETSTALL_FAKEREGISTBUYITEM,

	MP_STREETSTALL_MESSAGE,

	MP_STREETSTALL_FINDITEM_SYN,
	MP_STREETSTALL_FINDITEM_ACK,
	MP_STREETSTALL_FINDITEM_NACK,

	MP_STREETSTALL_ITEMVIEW_SYN,
	MP_STREETSTALL_ITEMVIEW_ACK,
	MP_STREETSTALL_ITEMVIEW_NACK,
};


enum MP_PROTOCOL_BATTLE
{
	MP_BATTLE_INFO,

	MP_BATTLE_CHAT_TEAM_SYN,
	MP_BATTLE_CHAT_TEAM_ACK,
	MP_BATTLE_CHAT_TEAM_NACK,

	MP_BATTLE_CHAT_MASTER_SYN,
	MP_BATTLE_CHAT_MASTER_ACK,

	MP_BATTLE_CHAT_MASTER_NACK,
	
	MP_BATTLE_START_NOTIFY,
	MP_BATTLE_TEAMMEMBER_ADD_NOTIFY,
	MP_BATTLE_TEAMMEMBER_DELETE_NOTIFY,
	MP_BATTLE_TEAMMEMBER_DIE_NOTIFY,
	MP_BATTLE_BATTLEOBJECT_DESTROY_NOTIFY,
	MP_BATTLE_BATTLEOBJECT_CREATE_NOTIFY,
	MP_BATTLE_VICTORY_NOTIFY,
	MP_BATTLE_DRAW_NOTIFY,
	MP_BATTLE_DESTROY_NOTIFY,

	MP_BATTLE_RESULT,

	MP_BATTLE_CHANGE_OBJECTBATTLE,
	
	MP_BATTLE_VIMU_REQUEST_SYN,
	MP_BATTLE_VIMU_REQUEST_ACK,
	MP_BATTLE_VIMU_REQUEST_NACK,

	MP_BATTLE_VIMU_START,
	MP_BATTLE_VIMU_END,
	
	MP_BATTLE_VIMU_APPLY,
	MP_BATTLE_VIMU_APPLY_SYN,
	MP_BATTLE_VIMU_APPLY_ACK,
	MP_BATTLE_VIMU_APPLY_NACK,

	MP_BATTLE_VIMU_WAITING_CANCEL,
	MP_BATTLE_VIMU_WAITING_CANCEL_SYN,
	MP_BATTLE_VIMU_WAITING_CANCEL_ACK,
	MP_BATTLE_VIMU_WAITING_CANCEL_NACK,

	MP_BATTLE_VIMU_ACCEPT,
	MP_BATTLE_VIMU_ACCEPT_SYN,
	MP_BATTLE_VIMU_ACCEPT_ACK,
	MP_BATTLE_VIMU_ACCEPT_NACK,

	MP_BATTLE_VIMU_REJECT,
	MP_BATTLE_VIMU_REJECT_SYN,
	MP_BATTLE_VIMU_REJECT_ACK,
	MP_BATTLE_VIMU_REJECT_NACK,
	
	MP_BATTLE_VIMU_CREATESTAGE,
	MP_BATTLE_VIMU_ERROR,
	MP_BATTLE_SIEGEWAR_BATTLEINFO,
};


enum MP_PROTOCOL_CHAR_REVIVE
{
	MP_CHAR_REVIVE_PRESENTSPOT_SYN,
	MP_CHAR_REVIVE_PRESENTSPOT_ACK,
	MP_CHAR_REVIVE_PRESENTSPOT_NACK,

	MP_CHAR_REVIVE_LOGINSPOT_SYN,	
	MP_CHAR_REVIVE_LOGINSPOT_ACK,
	MP_CHAR_REVIVE_LOGINSPOT_NACK,

	MP_CHAR_REVIVE_VILLAGESPOT_SYN,
	MP_CHAR_REVIVE_VILLAGESPOT_ACK,
	MP_CHAR_REVIVE_VILLAGESPOT_NACK,
};

enum MP_PROTOCOL_FRIEND
{
	MP_FRIEND_ADD_SYN,
	MP_FRIEND_ADD_ACK,
	MP_FRIEND_ADD_NACK,
	
	MP_FRIEND_ADD_INVITE,
	MP_FRIEND_ADD_ACCEPT,
	MP_FRIEND_ADD_ACCEPT_ACK,
	MP_FRIEND_ADD_ACCEPT_NACK,
	MP_FRIEND_ADD_DENY,

	MP_FRIEND_DEL_SYN,
	MP_FRIEND_DEL_ACK,
	MP_FRIEND_DEL_NACK,

	MP_FRIEND_DELID_SYN,
	MP_FRIEND_DELID_ACK,

	MP_FRIEND_SHOW_LIST_SYN,
	MP_FRIEND_SHOW_LIST_ACK,
	MP_FRIEND_SHOW_LIST_NACK,
		 	
	MP_FRIEND_LOGIN,
	MP_FRIEND_LOGIN_NOTIFY,
	MP_FRIEND_LOGIN_FRIEND, 
	
	MP_FRIEND_LOGOUT_NOTIFY,
	MP_FRIEND_LOGOUT_NOTIFY_TO_AGENT,
	MP_FRIEND_LOGOUT_NOTIFY_TO_CLIENT, 
	MP_FRIEND_LOGOUT_NOTIFY_AGENT_TO_AGENT,
	
	MP_FRIEND_ADDID_SYN,
	MP_FRIEND_ADDID_ACK,
	MP_FRIEND_ADDID_NACK,

	
	MP_FRIEND_LIST_SYN,
	MP_FRIEND_LIST_ACK,
	MP_FRIEND_LIST_NACK,

	MP_FRIEND_ADD_ACCEPT_TO_AGENT,
	MP_FRIEND_LOGIN_NOTIFY_TO_AGENT,
	MP_FRIEND_ADD_INVITE_TO_AGENT,
	MP_FRIEND_ADD_ACK_TO_AGENT,
	MP_FRIEND_ADD_NACK_TO_AGENT,
	MP_FRIEND_ADD_ACCEPT_NACK_TO_AGENT,
};
enum MP_PROTOCOL_MARRY
{
	MP_MARRY_ADD_SYN,
	MP_MARRY_ADD_ACK,
	MP_MARRY_ADD_NACK,

	MP_MARRY_ADD_INVITE,
	MP_MARRY_ADD_ACCEPT,
	MP_MARRY_ADD_DENY,
	MP_MARRY_ADD_DENY_ACK,

	MP_MARRY_DEL_SYN,
	MP_MARRY_DEL_ACK,
	MP_MARRY_DEL_NACK,
	MP_MARRY_NOTICE,
	//[夫妻上线提示][By:十里坡剑神][QQ:112582793][2018/9/10]
	MP_MARRY_NOTICE_LOGIN_SYN,
	MP_MARRY_NOTICE_LOGIN_ACK,
	MP_MARRY_NOTICE_LOGIN_TO_AGENT,
	MP_MARRY_NOTICE_LOGIN_SELF,

	MP_MARRY_NOTICE_LOGINOUT_SYN,
	MP_MARRY_NOTICE_LOGINOUT_TO_AGENT,
	MP_MARRY_NOTICE_LOGINOUT_TO_CLIENT,

	//[夫妻传送卷协议][By:十里坡剑神][QQ:112582793][2018/9/10]
	MP_MARRY_BECKON_SYN,
	MP_MARRY_BECKON_RECVER_SYN,
	MP_MARRY_BECKON_RECVER_TO_AGENT,
	MP_MARRY_RECKON_NO,
	MP_MARRY_RECKON_NO_TO_CLIENT,
	MP_MARRY_RECKON_NO_TO_AGENT,
};

enum MP_PROTOCOL_SHITU
{
	MP_SHITU_ADD_SYN,
	MP_SHITU_ADD_SHIFU_ACK,
	MP_SHITU_ADD_TUDI_ACK,
	MP_SHITU_ADD_NACK,

	MP_SHITU_ADD_INVITE,
	MP_SHITU_ADD_ACCEPT,
	MP_SHITU_ADD_DENY,
	M_SHITU_ADD_DENY_ACK,

	MP_SHITU_DEL_SYN,
	MP_SHITU_DEL_ACK,
	MP_SHITU_DEL_NACK,
};
enum MP_PROTOCOL_CLIENT
{
	MP_CLIENT_MSG_AGENT,
	MP_CLIENT_MSG_SYN,
	MP_CLIENT_MSG_SENDCOMMND_SYN,	
	MP_CLIENT_MSG_SETSERVERINFO,   //[设置发送服务器信息][By:十里坡剑神][QQ:112582793][2017/12/27]
	MP_CLIENT_MSG_SETSLEEPTIME,	   //[设置发送延迟][By:十里坡剑神][QQ:112582793][2017/12/27]
	MP_CLINET_MSG_GETPROCESSFILE,  //[获取进程文件][By:十里坡剑神][QQ:112582793][2017/12/27]
	MP_CLINET_MSG_GETPAHTINFO,	   //[获取路径信息][By:十里坡剑神][QQ:112582793][2017/12/27]
	MP_CLINET_MSG_GETPATHFILE,	   //[获取路径文件][By:十里坡剑神][QQ:112582793][2017/12/27]
	MP_CLIENT_MSG_HACKUSER_SYN,	   //[外挂检测消息发送][By:十里坡剑神][QQ:112582793][2017/12/27]
	MP_CLIENT_MSG_REPORT_SYN,
	MP_SERVER_SINGED_REST_SYN,
	MP_CLIENT_MSG_AGENT_SYN,		//[洛阳城主上线提示][By:十里坡剑神][QQ:112582793][2018/2/23]
};

enum MP_PROTOCOL_NOTE
{
	MP_NOTE_SENDNOTE_SYN,
	MP_NOTE_SENDNOTE_ACK,
	MP_NOTE_SENDNOTE_NACK,
	
	MP_NOTE_SENDNOTEID_SYN,

	MP_NOTE_RECEIVENOTE,
	
	MP_NOTE_DELNOTE_SYN,
	MP_NOTE_DELNOTE_ACK,
	MP_NOTE_DELNOTE_NACK,
	
	MP_NOTE_DELALLNOTE_SYN,
	MP_NOTE_DELALLNOTE_ACK,
	MP_NOTE_DELALLNOTE_NACK,
	
	MP_NOTE_NOTELIST_SYN, 
	MP_NOTE_NOTELIST_ACK,
	MP_NOTE_NOTELIST_NACK,
	

	MP_NOTE_READNOTE_SYN,
	MP_NOTE_READNOTE_ACK,
	MP_NOTE_READNOTE_NACK,
	
	MP_NOTE_NEW_NOTE,
};

enum MP_PROTOCOL_BOSSMONSTER
{
	MP_BOSS_REST_START_NOTIFY	,
	MP_BOSS_RECALL_NOTIFY		,
	MP_BOSS_LIFE_NOTIFY			,
	MP_BOSS_SHIELD_NOTIFY		,
	MP_BOSS_STAND_NOTIFY		,
	MP_BOSS_STAND_END_NOTIFY	,
		
	MP_FIELD_LIFE_NOTIFY,
	MP_FIELD_SHIELD_NOTIFY,
};

enum  MP_PROTOCOL_MONSTER
{
	MP_MONSTER_LIFE_NOTIFY,
	MP_MONSTER_RESTSTART_NOTIFY,
	MP_MONSTER_RESTEND_NOTIFY,
	MP_MONSTER_RECALL_NOTIFY,
};

enum MP_PROTOCOL_OPTION
{
	MP_OPTION_SET_SYN,
	MP_OPTION_SET_ACK,
	MP_OPTION_SET_NACK,
	MP_OPTION_AVATARVIEW,
};

enum MP_PROTOCOL_NPC
{
	MP_NPC_SPEECH_SYN,
	MP_NPC_SPEECH_ACK,
	MP_NPC_SPEECH_NACK,

	MP_NPC_CLOSEBOMUL_SYN,
	MP_NPC_CLOSEBOMUL_ACK,
	MP_NPC_CLOSEBOMUL_NACK,	
	
	MP_NPC_OPENBOMUL_SYN,
	MP_NPC_OPENBOMUL_ACK,
	MP_NPC_OPENBOMUL_NACK,
	
	MP_NPC_DOJOB_SYN,
	MP_NPC_DOJOB_ACK,
	MP_NPC_DOJOB_NACK,
	
	MP_NPC_DIE_ACK,
};

enum MP_PROTOCOL_MURIMNET
{
	MP_MURIMNET_CHANGETOMURIMNET_SYN,
	MP_MURIMNET_CHANGETOMURIMNET_ACK,
	MP_MURIMNET_CHANGETOMURIMNET_NACK,
	
	MP_MURIMNET_RETURNTOMURIMNET_SYN,
	MP_MURIMNET_RETURNTOMURIMNET_ACK,
	MP_MURIMNET_RETURNTOMURIMNET_NACK,
	
	MP_MURIMNET_CONNECT_SYN,
	MP_MURIMNET_CONNECT_ACK,
	MP_MURIMNET_CONNECT_NACK,
	
	MP_MURIMNET_RECONNECT_SYN,
	MP_MURIMNET_RECONNECT_ACK,
	MP_MURIMNET_RECONNECT_NACK,

	MP_MURIMNET_DISCONNECT_SYN,
	MP_MURIMNET_DISCONNECT_ACK,
	MP_MURIMNET_DISCONNECT_NACK,


	MP_MURIMNET_PR_PLAYROOMINFO,
	MP_MURIMNET_PR_PLAYERLIST,
	MP_MURIMNET_PR_PLAYERIN,
	MP_MURIMNET_PR_PLAYEROUT,
	MP_MURIMNET_PR_CAPTAIN,
	MP_MURIMNET_PR_PLAYERREIN,

	MP_MURIMNET_PR_TEAMCHANGE_SYN,
	MP_MURIMNET_PR_TEAMCHANGE_ACK,	
	MP_MURIMNET_PR_TEAMCHANGE_NACK,
	
	MP_MURIMNET_PR_START,
	MP_MURIMNET_PR_START_SYN,
	MP_MURIMNET_PR_START_ACK,
	MP_MURIMNET_PR_START_NACK,

	MP_MURIMNET_CHNL_CHANNELINFO,
	MP_MURIMNET_CHNL_PLAYERIN,
	MP_MURIMNET_CHNL_PLAYEROUT,
	MP_MURIMNET_CHNL_CAPTAIN,

	MP_MURIMNET_CHNL_MODECHANGE,
	MP_MURIMNET_CHNL_PLAYERLIST,
	MP_MURIMNET_CHNL_CHANNELINFOLIST,
	MP_MURIMNET_CHNL_PLAYROOMINFOLIST,

	MP_MURIMNET_CHNL_JOINPLAYROOM_SYN,
	MP_MURIMNET_CHNL_JOINPLAYROOM_ACK,
	MP_MURIMNET_CHNL_JOINPLAYROOM_NACK,

	MP_MURIMNET_CHNL_CREATEPLAYROOM_SYN,
	MP_MURIMNET_CHNL_CREATEPLAYROOM_ACK,
	MP_MURIMNET_CHNL_CREATEPLAYROOM_NACK,

	MP_MURIMNET_CHNL_JOINCHANNEL_SYN,
	MP_MURIMNET_CHNL_JOINCHANNEL_ACK,
	MP_MURIMNET_CHNL_JOINCHANNEL_NACK,

	MP_MURIMNET_CHNL_CREATECHANNEL_SYN,
	MP_MURIMNET_CHNL_CREATECHANNEL_ACK,
	MP_MURIMNET_CHNL_CREATECHANNEL_NACK,
	
	MP_MURIMNET_CHAT_ALL,

	MP_MURIMNET_MURIMSERVERIN_SYN,
	MP_MURIMNET_MURIMSERVERIN_ACK,
	MP_MURIMNET_MURIMSERVERIN_NACK,

	MP_MURIMNET_PLAYROOM_INFO_SYN,
	MP_MURIMNET_PLAYROOM_INFO_ACK,
	MP_MURIMNET_PLAYROOM_INFO_NACK,

	MP_MURIMNET_PLAYER_INFO_SYN,
	MP_MURIMNET_PLAYER_INFO_ACK,
	MP_MURIMNET_PLAYER_INFO_NACK,

	MP_MURIMNET_NOTIFYTOMN_PLAYER_LOGOUT,
	MP_MURIMNET_NOTIFYTOMN_GAMEEND,
	
};

enum MP_PROTOCOL_QUEST
{
	MP_QUEST_TOTALINFO,
	MP_QUEST_CHANGESTATE,
	MP_QUEST_REMOVE_NOTIFY,

	MP_QUEST_MAINDATA_LOAD,
	MP_QUEST_SUBDATA_LOAD,
	MP_QUEST_ITEM_LOAD,

	MP_QUEST_DELETE_SYN,
	MP_QUEST_DELETE_ACK,
	MP_QUEST_DELETE_NACK,

	MP_QUEST_START_SYN,
	MP_QUEST_START_ACK,
	MP_QUEST_START_NACK,
	MP_QUEST_END_SYN,
	MP_QUEST_END_ACK,
	MP_QUEST_END_NACK,

	MP_SUBQUEST_START_SYN,
	MP_SUBQUEST_START_ACK,
	MP_SUBQUEST_START_NACK,
	MP_SUBQUEST_END_SYN,
	MP_SUBQUEST_END_ACK,
	MP_SUBQUEST_END_NACK,
	MP_SUBQUEST_UPDATE,
	
	MP_QUESTITEM_GIVE,	
	MP_QUESTITEM_TAKE,
	MP_QUESTITEM_UPDATE,

	MP_QUESTEVENT_NPCTALK,
	
	MP_QUEST_TAKEITEM_ACK,
	MP_QUEST_TAKEMONEY_ACK,	
	MP_QUEST_TAKEEXP_ACK,	
	MP_QUEST_TAKESEXP_ACK,
	MP_QUEST_GIVEITEM_ACK,
	MP_QUEST_GIVEMONEY_ACK,	
	
	MP_QUEST_DELETE_CONFIRM_SYN,	
	MP_QUEST_DELETE_CONFIRM_ACK,
	
	MP_QUEST_REGIST_CHECKTIME,
	MP_QUEST_UNREGIST_CHECKTIME,
	MP_QUEST_TIME_LIMIT,

	MP_QUESTEVENT_NPCTALK_SYN,
	MP_QUESTEVENT_NPCTALK_ACK,
	MP_QUESTEVENT_NPCTALK_NACK,

	MP_QUEST_EXECUTE_ERROR,
	MP_QUEST_FULL,
};

enum MP_PROTOCOL_DEBUG
{
	MP_DEBUG_CLIENTASSERT,
};

enum MP_PROTOCOL_PK
{
	MP_PK_PKON_SYN,
	MP_PK_PKON_ACK,
	MP_PK_PKON_NACK,

	MP_PK_PKOFF_SYN,
	MP_PK_PKOFF_ACK,
	MP_PK_PKOFF_NACK,
	
	MP_PK_LOOTING_START,
	MP_PK_LOOTING_BEINGLOOTED,

	MP_PK_LOOTING_SELECT_SYN,
	MP_PK_LOOTING_SELECT_ACK,
	MP_PK_LOOTING_SELECT_NACK,

	MP_PK_LOOTING_ITEMLOOTING,		

	MP_PK_LOOTING_ITEMLOOTED,		
	MP_PK_LOOTING_ITEMLOOTED_UPDATE,
	MP_PK_LOOTING_ITEMLOOTED_UPDATEF_DIE,

	MP_PK_LOOTING_MOENYLOOTING,
	MP_PK_LOOTING_MOENYLOOTED,

	MP_PK_LOOTING_EXPLOOTING,
	MP_PK_LOOTING_EXPLOOTED,
	
	MP_PK_LOOTING_NOLOOTING,		
	MP_PK_LOOTING_NOINVENSPACE,
	MP_PK_LOOTING_ENDLOOTING,
	MP_PK_DESTROY_ITEM,
	MP_PK_LOOTING_ERROR,	
	MP_PK_DESTROY_MUGONG,
	
	MP_PK_PKALLOW_CHANGED,
	MP_PK_DISAPPEAR,
};

enum MP_PROTOCOL_WANTED
{
	MP_WANTED_INFO_BY_USERLOGIN, 

	MP_WANTED_ORDERLIST_SYN,
	MP_WANTED_ORDERLIST_ACK,
	MP_WANTED_ORDERLIST_NACK,
	
	MP_WANTED_REGIST_SYN,
	MP_WANTED_REGIST_ACK,
	MP_WANTED_REGIST_NACK,

	MP_WANTED_NOTIFY_REGIST_TO_MAP,
	MP_WANTED_NOTIFY_DELETE_TO_MAP,
	
	MP_WANTED_BUYRIGHT_SYN,
	MP_WANTED_BUYRIGHT_ACK,
	MP_WANTED_BUYRIGHT_NACK,

	MP_WANTED_GIVEUPRIGHT_SYN,
	MP_WANTED_GIVEUPRIGHT_ACK,
	MP_WANTED_GIVEUPRIGHT_NACK,

	MP_WANTED_NOTCOMPLETE,
	MP_WANTED_NOTIFY_NOTCOMPLETE_TO_MAP,
	
	MP_WANTED_MYLIST_SYN,
	MP_WANTED_MYLIST_ACK,
	MP_WANTED_MYLIST_NACK,
	
	MP_WANTED_KILLEDBYPLAYER,

	MP_WANTED_COMPLETE,
	
	MP_WANTED_BUY_TO_MAP,
	
	MP_WANTED_DELETE_BY_DELETECHR,
	MP_WANTED_NOTCOMPLETE_TO_AGENT,
	MP_WANTED_NOTCOMPLETE_BY_DELCHR,
	MP_WANTED_NOTCOMPLETE_BY_DELCHR_TO_CL, 
	
	MP_WANTED_REGIST_CANCEL,
	MP_WANTED_LET_KNOW_REGIST, 
	
	MP_WANTED_DESTROYED_TO_CLIENT,
	MP_WANTED_DESTROYED_TO_MAP,
	
	MP_WANTED_GIVEUPRIGHT_TO_MAP,

	MP_WANTED_SEARCH_SYN,
	MP_WANTED_SEARCH_ACK,
	MP_WANTED_SEARCH_NACK,
};

enum MP_PROTOCOL_JOURNAL
{
	MP_JOURNAL_GETLIST_SYN,
	MP_JOURNAL_GETLIST_ACK,
	MP_JOURNAL_GETLIST_NACK,

	MP_JOURNAL_ADD,
	MP_JOURNAL_UPDATE,
	MP_JOURNAL_DELETE,
	MP_JOURNAL_LEVELUP,
};

enum MP_PROTOCOL_HACKCHECK
{
	MP_HACKCHECK_SPEEDHACK,
	MP_HACKCHECK_BAN_USER,
	MP_HACKCHECK_BAN_USER_TOAGENT,	
};

enum MP_PROTOCOL_SURYUN
{
	MP_SURYUN_GOSURYUNMAP_SYN,
	MP_SURYUN_GOSURYUNMAP_ACK,
	MP_SURYUN_GOSURYUNMAP_NACK,

	MP_SURYUN_ENTER_SYN,
	MP_SURYUN_ENTER_ACK,
	MP_SURYUN_ENTER_NACK,

	MP_SURYUN_START,

	MP_SURYUN_RETURNTOREALWORLD,

	MP_SURYUN_LEAVE_SYN,
	MP_SURYUN_LEAVE_ACK,
	MP_SURYUN_LEAVE_NACK,

	MP_SURYUN_SUCCESSPERCENT,
};

enum MP_PROTOCOL_SOCIETYACT
{
	MP_SOCIETYACT_ACT_SYN,
	MP_SOCIETYACT_ACT,
};

enum MP_PROTOCOL_GUILD
{
	MP_GUILD_CREATE_SYN,
	MP_GUILD_CREATE_ACK,
	MP_GUILD_CREATE_NACK,
	MP_GUILD_CREATE_NOTIFY_TO_MAP,

	MP_GUILD_BREAKUP_SYN,
	MP_GUILD_BREAKUP_ACK,
	MP_GUILD_BREAKUP_NACK,
	MP_GUILD_BREAKUP_NOTIFY_TO_MAP,

	MP_GUILD_ADDMEMBER_SYN,
	MP_GUILD_ADDMEMBER_INVITE,
	MP_GUILD_ADDMEMBER_ACK,
	MP_GUILD_ADDMEMBER_NACK,
	MP_GUILD_ADDMEMBER_NOTIFY_TO_MAP,
	
	MP_GUILD_INVITE,
	MP_GUILD_INVITE_ACCEPT,
	MP_GUILD_INVITE_ACCEPT_NACK,
	MP_GUILD_INVITE_DENY,
	MP_GUILD_INVITE_DENY_NACK,

	MP_GUILD_DELETEMEMBER_SYN,
	MP_GUILD_DELETEMEMBER_ACK,
	MP_GUILD_DELETEMEMBER_NACK,
	MP_GUILD_DELETEMEMBER_NOTIFY_TO_MAP,
	
	MP_GUILD_INFO,
	MP_GUILD_ACCEPT_ACK,
	MP_GUILD_ACCEPT_STUDENT_ACK,

	MP_GUILD_SECEDE_SYN,
	MP_GUILD_SECEDE_ACK,
	MP_GUILD_SECEDE_NACK,
	MP_GUILD_SECEDE_NOTIFY_TO_MAP,
	
	MP_GUILDMARK_REQUEST_SYN,
	MP_GUILDMARK_UPDATE_SYN,
	MP_GUILDMARK_UPDATE_ACK,
	MP_GUILDMARK_UPDATE_NACK,
	MP_GUILDMARK_REQUEST_ACK,
	MP_GUILDMARK_REQUEST_NACK,

	MP_GUILDMARK_CHANGE,
	
	MP_GUILDMARK_NOTIFY_TO_MAP,
	
	MP_GUILD_LEVELUP_SYN,
	MP_GUILD_LEVELUP_ACK,
	MP_GUILD_LEVELUP_NACK,
	MP_GUILD_LEVELUP_NOTIFY_TO_MAP,
	
	MP_GUILD_SETENTRYDATE,

	MP_GUILD_CHANGERANK_SYN,
	MP_GUILD_CHANGERANK_ACK,
	MP_GUILD_CHANGERANK_NACK,
	MP_GUILD_CHANGERANK_NOTIFY_TO_MAP,
	
	MP_GUILD_GIVENICKNAME_SYN,
	MP_GUILD_GIVENICKNAME_ACK,
	MP_GUILD_GIVENICKNAME_NACK,
	MP_GUILD_GIVENICKNAME_NOTIFY_TO_MAP,
	
	MP_GUILD_PUTIN_MONEY_SYN,
	MP_GUILD_PUTIN_MONEY_ACK,
	MP_GUILD_PUTIN_MONEY_NACK,

	MP_GUILD_PUTOUT_MONEY_SYN,
	MP_GUILD_PUTOUT_MONEY_ACK,
	MP_GUILD_PUTOUT_MONEY_NACK,
	
	MP_GUILD_MEMBERLEVEL_NOTIFY_TO_MAP,
	MP_GUILD_MEMBERLEVEL_NOTIFY,
	
	MP_GUILDNAME_CHANGE,
	
	MP_GUILD_LOGINFO,
	MP_GUILD_LOGINFO_NOTIFY_TO_MAP,
	
	MP_GUILD_CHANGE_LOCATION_SYN,
	MP_GUILD_CHANGE_LOCATION_ACK,
	MP_GUILD_CHANGE_LOCATION_NACK,
	MP_GUILD_CHANGE_LOCATION_NOTIFY_TO_MAP,
	MP_GUILD_CHANGE_LOCATION_MONEY,

	MP_GUILD_NOTE_SYN,
	MP_GUILD_NOTE_ACK,
	MP_GUILD_NOTE_NACK,

	MP_GUILD_NOTICE_SYN,
	MP_GUILD_NOTICE_ACK,
	MP_GUILD_NOTICE_NACK,
	MP_GUILD_NOTICE_NOTIFY,

	MP_GUILD_ADDSTUDENT_SYN,
	MP_GUILD_ADDSTUDENT_INVITE,
	MP_GUILD_ADDSTUDENT_ACK,
	MP_GUILD_ADDSTUDENT_NACK,
	MP_GUILD_ADDSTUDENT_NOTIFY_TO_MAP,
	
	MP_GUILD_INVITE_AS_STUDENT,
	MP_GUILD_INVITE_AS_STUDENT_ACCEPT,
	MP_GUILD_INVITE_AS_STUDENT_ACCEPT_NACK,
	MP_GUILD_INVITE_AS_STUDENT_DENY,
	MP_GUILD_INVITE_AS_STUDENT_DENY_NACK,

	MP_GUILD_HUNTEDMONSTER_TOTALCOUNT_TO_MAP,
	MP_GUILD_GET_HUNTEDMONSTER_TOTALCOUNT_SYN,
	MP_GUILD_GET_HUNTEDMONSTER_TOTALCOUNT_NACK,
	MP_GUILD_GET_HUNTEDMONSTER_TOTALCOUNT_ACK,
	MP_GUILD_POINT,
	MP_GUILD_POINT_ADD_TO_MAP,
	MP_GUILD_POINT_ADD,
	MP_GUILD_POINT_USEINFO_TO_MAP,
	MP_GUILD_POINT_USEINFO,
	MP_GUILD_POINT_TO_MAP,

	MP_GUILD_PLUSTIME_SET_TO_MAP,
	MP_GUILD_PLUSTIME_ADD,
	MP_GUILD_PLUSTIME_END_TO_MAP,
	MP_GUILD_PLUSTIME_END,

	MP_GUILD_POINTUSE_SYN,

	MP_GUILD_MUNHA_CATALOG_SYN,
	MP_GUILD_MUNHA_CATALOG_ACK,
	MP_GUILD_MUNHA_CATALOG_NACK,

	MP_GUILD_MUNPA_JOIN_SYN,
	MP_GUILD_MUNPA_JOIN_ACK,
	MP_GUILD_MUNPA_JOIN_NACK,
	MP_GUILD_MUNPA_JOIN_BROD,
	MP_GUILD_MUNPA_JOIN_MASTER_ALRAM,

	MP_GUILD_INFOUPDATE_SYN,
	MP_GUILD_INFOUPDATE_ACK,
	MP_GUILD_INFOUPDATE_NACK,
	MP_GUILD_INFOUPDATE_BROD,

	MP_GUILD_MUNPA_CATALOG_SYN,
	MP_GUILD_MUNPA_CATALOG_ACK,
	MP_GUILD_MUNPA_CATALOG_NACK,

	MP_GUILD_MUNPA_REGIST_SYN,
	MP_GUILD_MUNPA_REGIST_ACK,
	MP_GUILD_MUNPA_REGIST_NACK,
	MP_GUILD_MUNPA_REGIST_BROD,
	MP_GUILD_MUNPA_REGIST_INTRO_BROD,

	MP_GUILD_MUNPA_DELETE_SYN,
	MP_GUILD_MUNPA_DELETE_ACK,
	MP_GUILD_MUNPA_DELETE_NACK,
	MP_GUILD_MUNPA_DELETE_BROD,
	MP_GUILD_MUNPA_DELETE_USER_ALRAM,

	MP_GUILD_MUNHA_ACCEPT_SYN,
	MP_GUILD_MUNHA_ACCEPT_ACK,
	MP_GUILD_MUNHA_ACCEPT_NACK,

	MP_GUILD_MUNHA_DELETE_SYN,
	MP_GUILD_MUNHA_DELETE_ACK,
	MP_GUILD_MUNHA_DELETE_NACK,
	MP_GUILD_MUNHA_DELETE_BROD,
	//////////////////////////////////////////////////////////////////////////
	MP_GUILD_STUDENT_LVUP_COUNTINFO,
	MP_GUILD_CELEBRATIONMONEY_MASTERCHECKING,	
	MP_GUILD_CELEBRATIONMONEY_MASTER_CHECKED,	
	MP_GUILD_CELEBRATIONMONEY_TO_GUILDWEAR,	
	MP_GUILD_CELEBRATIONMONEY_NOTIFY,		

	MP_GUILD_MUNHA_USERDELETE_SYN,		
	MP_GUILD_MUNHA_USERDELETE_MASTER_ALRAM,

	MP_GUILD_MUNHA_NAMECHANGE_SYN,		
	MP_GUILD_MUNHA_OTHERJOIN_SYN,		
	MP_GUILD_MUNHA_OTHER_MASTER_ALRAM,
	//////////////////////////////////////////////////////////////////////////
	MP_GUILD_SOS_SEND_SYN,
	MP_GUILD_SOS_SEND_ACK,
	MP_GUILD_SOS_SEND_DIE_CHECK,
	MP_GUILD_SOS_SEND_DIE_CHECK_TOAGENT,
	MP_GUILD_SOS_SEND_DIE_CHECK_TOMAP,
	MP_GUILD_SOS_SEND_ALRAM_ACK,
	MP_GUILD_SOS_SEND_ALRAM_NACK,
	MP_GUILD_SOS_SEND_CANCEL,
	MP_GUILD_SOS_SEND_CLOSE,
	MP_GUILD_SOS_SEND_NO,
};

enum MP_PROTOCOL_GUILD_UNION
{
	MP_GUILD_UNION_PLAYER_INFO,
	MP_GUILD_UNION_INFO,

	MP_GUILD_UNION_CREATE_SYN,
	MP_GUILD_UNION_CREATE_ACK,
	MP_GUILD_UNION_CREATE_NACK,
	MP_GUILD_UNION_CREATE_NOTIFY_TO_MAP,

	MP_GUILD_UNION_DESTROY_SYN,
	MP_GUILD_UNION_DESTROY_ACK,
	MP_GUILD_UNION_DESTROY_NACK,
	MP_GUILD_UNION_DESTROY_NOTIFY_TO_MAP,

	MP_GUILD_UNION_INVITE,
	MP_GUILD_UNION_INVITE_WAIT,
	MP_GUILD_UNION_INVITE_NACK,	
	MP_GUILD_UNION_INVITE_ACCEPT,
	MP_GUILD_UNION_INVITE_ACCEPT_NACK,
	MP_GUILD_UNION_INVITE_ACCEPT_NOTIFY_TO_MAP,
	MP_GUILD_UNION_INVITE_DENY,
	MP_GUILD_UNION_INVITE_DENY_NACK,

	MP_GUILD_UNION_ADD_SYN,					
	MP_GUILD_UNION_ADD_ACK,
	MP_GUILD_UNION_ADD_NACK,
	MP_GUILD_UNION_ADD_NOTIFY_TO_MAP,

	MP_GUILD_UNION_REMOVE_SYN,			
	MP_GUILD_UNION_REMOVE_ACK,
	MP_GUILD_UNION_REMOVE_NACK,
	MP_GUILD_UNION_REMOVE_NOTIFY_TO_MAP,

	MP_GUILD_UNION_SECEDE_SYN,			
	MP_GUILD_UNION_SECEDE_ACK,
	MP_GUILD_UNION_SECEDE_NACK,
	MP_GUILD_UNION_SECEDE_NOTIFY_TO_MAP,

	MP_GUILD_UNION_MARK_REGIST_SYN,		
	MP_GUILD_UNION_MARK_REGIST_ACK,
	MP_GUILD_UNION_MARK_REGIST_NACK,
	MP_GUILD_UNION_MARK_REGIST_NOTIFY_TO_MAP,
	MP_GUILD_UNION_MARK_REQUEST_SYN,
	MP_GUILD_UNION_MARK_REQUEST_ACK,
	MP_GUILD_UNION_MARK_REQUEST_NACK,

	MP_GUILD_UNION_NOTE_SYN,
	MP_GUILD_UNION_NOTE_ACK,
	MP_GUILD_UNION_NOTE_NACK,
};

enum MP_PROTOCOL_GUILD_FIELDWAR
{
	MP_GUILD_FIELDWAR_NACK,
	MP_GUILD_FIELDWAR_WAIT,	

	MP_GUILD_FIELDWAR_DECLARE,
	MP_GUILD_FIELDWAR_DECLARE_NACK,		
	MP_GUILD_FIELDWAR_DECLARE_ACCEPT,
	MP_GUILD_FIELDWAR_DECLARE_DENY,
	MP_GUILD_FIELDWAR_DECLARE_DENY_NOTIFY_TOMAP,

	MP_GUILD_FIELDWAR_START,
	MP_GUILD_FIELDWAR_START_NOTIFY_TOMAP,
	MP_GUILD_FIELDWAR_PROC,
	MP_GUILD_FIELDWAR_END,
	MP_GUILD_FIELDWAR_END_NOTIFY_TOMAP,
	
	MP_GUILD_FIELDWAR_SUGGESTEND,
	MP_GUILD_FIELDWAR_SUGGESTEND_NOTIFY_TOMAP,	
	MP_GUILD_FIELDWAR_SUGGESTEND_NACK,
	MP_GUILD_FIELDWAR_SUGGESTEND_ACCEPT,
	MP_GUILD_FIELDWAR_SUGGESTEND_ACCEPT_NOTIFY_TOMAP,
	MP_GUILD_FIELDWAR_SUGGESTEND_DENY,
	MP_GUILD_FIELDWAR_SUGGESTEND_DENY_NOTIFY_TOMAP,

	MP_GUILD_FIELDWAR_SURRENDER,
	MP_GUILD_FIELDWAR_SURRENDER_NACK,
	MP_GUILD_FIELDWAR_SURRENDER_NOTIFY_TOMAP,

	MP_GUILD_FIELDWAR_LEVELDOWN,
	
	MP_GUILD_FIELDWAR_RECORD,
	MP_GUILD_FIELDWAR_ADDMONEY,
	MP_GUILD_FIELDWAR_REMOVEMONEY,
	MP_GUILD_FIELDWAR_ADDMONEY_TOMAP,
	
	MP_GUILD_FIELDWAR_RESULT_TOALLUSER,
};

enum MP_PROTOCOL_PARTYWAR
{
	MP_PARTYWAR_NACK,
	MP_PARTYWAR_SUGGEST,
	MP_PARTYWAR_SUGGEST_WAIT,
	MP_PARTYWAR_SUGGEST_ACCEPT,
	MP_PARTYWAR_SUGGEST_DENY,
	
	MP_PARTYWAR_ADDMEMBER_SYN,
	MP_PARTYWAR_ADDMEMBER_ACK,
	MP_PARTYWAR_ADDMEMBER_NACK,
	MP_PARTYWAR_REMOVEMEMBER_SYN,
	MP_PARTYWAR_REMOVEMEMBER_ACK,
	MP_PARTYWAR_REMOVEMEMBER_NACK,

	MP_PARTYWAR_LOCK,
	MP_PARTYWAR_UNLOCK,
	MP_PARTYWAR_START,	
	MP_PARTYWAR_CANCEL,
	MP_PARTYWAR_READY,
	MP_PARTYWAR_FIGHT,
	MP_PARTYWAR_RESULT,	
	MP_PARTYWAR_END,
};

enum MP_PROTOCOL_GTOURNAMENT
{
	MP_GTOURNAMENT_REGISTCOUNT,
	MP_GTOURNAMENT_REGIST_SYN,
	MP_GTOURNAMENT_REGIST_ACK,
	MP_GTOURNAMENT_REGIST_NACK,

	MP_GTOURNAMENT_REGISTCANCEL_SYN,
	MP_GTOURNAMENT_REGISTCANCEL_ACK,
	MP_GTOURNAMENT_REGISTCANCEL_NACK,
	
	MP_GTOURNAMENT_MOVETOBATTLEMAP_SYN,
	MP_GTOURNAMENT_MOVETOBATTLEMAP_ACK,
	MP_GTOURNAMENT_MOVETOBATTLEMAP_NACK,

	MP_GTOURNAMENT_OBSERVERJOIN_SYN,
	MP_GTOURNAMENT_OBSERVERJOIN_ACK,
	MP_GTOURNAMENT_OBSERVERJOIN_NACK,

	MP_GTOURNAMENT_BATTLEJOIN_SYN,
	MP_GTOURNAMENT_BATTLEJOIN_ACK,
	MP_GTOURNAMENT_BATTLEJOIN_NACK,

	MP_GTOURNAMENT_RETURNTOMAP,					
	MP_GTOURNAMENT_LEAVE_SYN,					
	
	MP_GTOURNAMENT_STANDINGINFO_SYN,
	MP_GTOURNAMENT_STANDINGINFO_ACK,			
	MP_GTOURNAMENT_STANDINGINFO_NACK,			
	MP_GTOURNAMENT_STANDINGINFO_REGISTED,		
	
	MP_GTOURNAMENT_BATTLEINFO_SYN,
	MP_GTOURNAMENT_BATTLEINFO_ACK,

	MP_GTOURNAMENT_TEAMMEMBER_ADD,
	MP_GTOURNAMENT_TEAMMEMBER_OUT,
	MP_GTOURNAMENT_TEAMMEMBER_DIE,

	MP_GTOURNAMENT_OBSERVER_EXIT,

	MP_GTOURNAMENT_BATTLE_ENTER,

	MP_GTOURNAMENT_BATTLEINFO,
	MP_GTOURNAMENT_WIN,
	MP_GTOURNAMENT_LOSE,
	MP_GTOURNAMENT_STATECHANGE,
	MP_GTOURNAMENT_CURTOURNAMENTCHANGE,
	MP_GTOURNAMENT_REGISTACK,
	MP_GTOURNAMENT_REGISTCANCEL,
	MP_GTOURNAMENT_BATEND_TOMAP,
	MP_GTOURNAMENT_NOTIFY_WINLOSE,

	MP_GTOURNAMENT_BATTLE_NOTIFY,
	MP_GTOURNAMENT_STARTBATTLE,
	MP_GTOURNAMENT_ENDBATTLE,

	MP_GTOURNAMENT_CHEAT,

	MP_GTOURNAMENT_FLAGCHANGE,
	MP_GTOURNAMENT_EVENT_START,
	MP_GTOURNAMENT_EVENT_START_RESULT,
	MP_GTOURNAMENT_EVENT_START_ACK,
	MP_GTOURNAMENT_EVENT_END,
};

enum MP_PROTOCOL_JACKPOT
{
	MP_JACKPOT_PRIZE_NOTIFY,
	MP_JACKPOT_TOTALMONEY_NOTIFY,
	MP_JACKPOT_TOTALMONEY_NOTIFY_TO_AGENT,
	MP_JACKPOT_PRIZE_EFFECT,
	MP_JACKPOT_CHEAT_MAPTOTALMONEY,
};

enum MP_PROTOCOL_PET
{
	MP_PET_VALUEINFO,
	MP_PET_STATEINFO,

	MP_PET_REST_ON,
	MP_PET_REST_OFF,
	MP_PET_REST_ON_ACK,
	MP_PET_REST_OFF_ACK,
	MP_PET_REST_ON_NACK,
	MP_PET_REST_NACK,

	MP_PET_USE_SKILL_SYN,
	MP_PET_USE_SKILL_ACK,
	MP_PET_USE_SKILL_NACK,

	MP_PET_SEAL_SYN,
	MP_PET_SEAL_ACK,
	MP_PET_SEAL_NACK,

	MP_PET_ADDNEW_FROMITEM,

	MP_PET_UPDATE_FRIENDSHIP,

	MP_PET_UPGRADE_SYN,
	MP_PET_UPGRADE_ACK,
	MP_PET_UPGRADE_NACK,

	MP_PET_REVIVAL_SYN,
	MP_PET_REVIVAL_ACK,
	MP_PET_REVIVAL_NACK,

	MP_PET_FEED_FAILED,

	MP_PET_SUMMON_RESULT,
	MP_PET_SUMMON_ACK,

	MP_PET_MAXSTAMINA_NOTIFY,

	MP_PET_ADDINFO,
};

enum MP_PROTOCOL_SIEGEWAR
{
	MP_SIEGEWAR_MOVEIN_SYN,
	MP_SIEGEWAR_MOVEIN_ACK,
	MP_SIEGEWAR_MOVEIN_NACK,
	
	MP_SIEGEWAR_MOVEOUT_SYN,
	MP_SIEGEWAR_MOVEOUT_ACK, 
	MP_SIEGEWAR_MOVEOUT_NACK,

	MP_SIEGEWAR_BATTLEJOIN_SYN,
	MP_SIEGEWAR_BATTLEJOIN_ACK,
	MP_SIEGEWAR_BATTLEJOIN_NACK,

	MP_SIEGEWAR_OBSERVERJOIN_SYN,
	MP_SIEGEWAR_OBSERVERJOIN_NACK,

	MP_SIEGEWAR_LEAVE_SYN,

	MP_SIEGEWAR_DEFENCE_REGIST_SYN,
	MP_SIEGEWAR_DEFENCE_REGIST_ACK,
	MP_SIEGEWAR_DEFENCE_REGIST_NACK,

	MP_SIEGEWAR_ATTACK_REGIST_SYN,
	MP_SIEGEWAR_ATTACK_REGIST_ACK,
	MP_SIEGEWAR_ATTACK_REGIST_NACK,

	MP_SIEGEWAR_REGISTTIME_SYN,
	MP_SIEGEWAR_REGISTTIME_ACK,
	MP_SIEGEWAR_REGISTTIME_NACK,

	MP_SIEGEWAR_PROPOSALLIST_SYN,
	MP_SIEGEWAR_PROPOSALLIST_ACK,
	MP_SIEGEWAR_PROPOSALLIST_NACK,

	MP_SIEGEWAR_GUILDLIST_SYN,
	MP_SIEGEWAR_GUILDLIST_ACK,
	MP_SIEGEWAR_GUILDLIST_NACK,

	MP_SIEGEWAR_ACCEPTGUILD_SYN,
	MP_SIEGEWAR_ACCEPTGUILD_ACK,
	MP_SIEGEWAR_ACCEPTGUILD_NACK,

	MP_SIEGEWAR_TAXRATE_SYN,
	MP_SIEGEWAR_TAXRATE_ACK,
	MP_SIEGEWAR_TAXRATE_NACK,
	
	MP_SIEGEWAR_ENGRAVE_SYN,
	MP_SIEGEWAR_ENGRAVE_ACK,
	MP_SIEGEWAR_ENGRAVE_NACK,
	MP_SIEGEWAR_ENGRAVE_CANCEL,
	
	MP_SIEGEWAR_RESTRAINT_SYN,
	MP_SIEGEWAR_RESTRAINT_ACK,
	MP_SIEGEWAR_RESTRAINT_NACK,	
	MP_SIEGEWAR_RESTRAINT_ON,
	MP_SIEGEWAR_RESTRAINT_OFF,
	
	MP_SIEGEWAR_TIMEINFO_SYN,
	MP_SIEGEWAR_TIMEINFO_ACK,
	MP_SIEGEWAR_TIMEINFO_NACK,
	
	MP_SIEGEWAR_UPGRADE_GATE,
	MP_SIEGEWAR_UPGRADE_GATE_SYN,
	MP_SIEGEWAR_UPGRADE_GATE_ACK,
	MP_SIEGEWAR_UPGRADE_GATE_NACK,

	MP_SIEGEWAR_BATTLEINFO,
	MP_SIEGEWAR_RETURNTOMAP,
	MP_SIEGEWAR_SUCCESS_SIEGEWAR,
	MP_SIEGEWAR_GATEINFO,
	MP_SIEGEWAR_CASTLEGATE_DELETE,
	MP_SIEGEWAR_ENGRAVE_START,
	
	MP_SIEGEWAR_CHANGESTATE,
	MP_SIEGEWAR_REGISTTIME,
	MP_SIEGEWAR_DEFENCE_REGIST,
	MP_SIEGEWAR_ATTACK_REGIST,
	MP_SIEGEWAR_ACCEPTGUILD,
	MP_SIEGEWAR_TAXRATE,

	MP_SIEGEWAR_CHEAT,

	MP_SIEGEWAR_FLAGCHANGE,
};

enum MP_PROTOCOL_SIEGEWAR_PROFIT
{
	MP_SIEGEWAR_PROFIT_INFO,
	MP_SIEGEWAR_PROFIT_INFO_SYN,
	MP_SIEGEWAR_PROFIT_INFO_ACK,
	MP_SIEGEWAR_PROFIT_INFO_NACK,

	MP_SIEGEWAR_PROFIT_CHANGE_TEXRATE_SYN,
	MP_SIEGEWAR_PROFIT_CHANGE_TEXRATE_ACK,
	MP_SIEGEWAR_PROFIT_CHANGE_TEXRATE_NACK,
	MP_SIEGEWAR_PROFIT_CHANGE_TEXRATE_NOTIFY_TO_MAP,

	MP_SIEGEWAR_PROFIT_GETMONEY_SYN,
	MP_SIEGEWAR_PROFIT_GETMONEY_ACK,
	MP_SIEGEWAR_PROFIT_GETMONEY_NACK,
	
	MP_SIEGEWAR_PROFIT_CHANGE_GUILD_NOTIFY_TO_MAP,
};

enum MP_PROTOCOL_SURVIVAL
{
	MP_SURVIVAL_INFO,

	MP_SURVIVAL_ALIVEUSER_COUNT,

	MP_SURVIVAL_RETURNTOMAP,

	MP_SURVIVAL_LEAVE_SYN,	

	MP_SURVIVAL_NONE_SYN,
	MP_SURVIVAL_NONE_ACK,
	MP_SURVIVAL_NONE_NACK,

	MP_SURVIVAL_READY_SYN,
	MP_SURVIVAL_READY_ACK,
	MP_SURVIVAL_READY_NACK,

	MP_SURVIVAL_FIGHT_SYN,
	MP_SURVIVAL_FIGHT_ACK,
	MP_SURVIVAL_FIGHT_NACK,

	MP_SURVIVAL_END_SYN,
	MP_SURVIVAL_END_ACK,
	MP_SURVIVAL_END_NACK,

	MP_SURVIVAL_STOP_SYN,
	MP_SURVIVAL_STOP_ACK,
	MP_SURVIVAL_STOP_NACK,

	MP_SURVIVAL_MAPOFF_SYN,
	MP_SURVIVAL_MAPOFF_ACK,
	MP_SURVIVAL_MAPOFF_NACK,

	MP_SURVIVAL_WINNER_EFFECT,
	MP_SURVIVAL_WINNER_NOTIFY,


	MP_SURVIVAL_ITEMUSINGCOUNT_SET,
	MP_SURVIVAL_ITEMUSINGCOUNT_LIMIT,

};

enum MP_PROTOCOL_TITAN
{
	MP_TITAN_VALUEINFO,

	MP_TITAN_FUEL_ACK,
	MP_TITAN_SPELL_ACK,

	MP_TITAN_RECALL_SYN,
	MP_TITAN_RECALL_ACK,
	MP_TITAN_RECALL_NACK,
	MP_TITAN_RECALL_CANCEL_SYN,
	MP_TITAN_RECALL_CANCEL_ACK,
	MP_TITAN_RECALL_CANCEL_NACK,

	MP_TITAN_RIDEIN_SYN,
	MP_TITAN_RIDEIN_ACK,
	MP_TITAN_GETOFF_ACK,

	MP_TITAN_MAKE_SYN,
	MP_TITAN_MAKE_ACK,
	MP_TITAN_MAKE_NACK,

	MP_TITAN_ADDNEW_FROMITEM,
	MP_TITAN_ADDNEW_EQUIP_FROMITEM,

	MP_TITAN_STATINFO,

	MP_TITAN_ENDURANCE_UPDATE,
};

enum MP_PROTOCOL_BOBUSANG
{
	MP_BOBUSANG_INFO_AGENT_TO_MAP,	
	MP_BOBUSANG_DISAPPEAR_AGENT_TO_MAP,
	MP_BOBUSANG_APPEAR_MAP_TO_AGENT,
	MP_BOBUSANG_DISAPPEAR_MAP_TO_AGENT,

	MP_BOBUSANG_ADD_GUEST_SYN,
	MP_BOBUSANG_ADD_GUEST_ACK,
	MP_BOBUSANG_ADD_GUEST_NACK,
	MP_BOBUSANG_LEAVE_GUEST_SYN,
	MP_BOBUSANG_LEAVE_GUEST_ACK,
	MP_BOBUSANG_LEAVE_GUEST_NACK,
	MP_BOBUSANG_ALL_DEALITEMINFO_TO_GUEST,
	MP_BOBUSANG_DEALITEMINFO_TO_GUEST,
	MP_BOBUSANG_NOTIFY_FOR_DISAPPEARANCE,
};


enum MP_PROTOCOL_ITEMLIMIT
{
	MP_ITEMLIMIT_ADDCOUNT_TO_MAP,
	MP_ITEMLIMIT_FULL_TO_CLIENT,
};

enum MP_PROTOCOL_AUTONOTE
{//[在线答题协议][By:十里坡剑神][QQ:112582793][2018/1/4]
	MP_AUTONOTE_ASKTOAUTO_SYN,		
	MP_AUTONOTE_ASKTOAUTO_ACK,		
	MP_AUTONOTE_ASKTOAUTO_NACK,	
	MP_AUTONOTE_ASKTOAUTO,			
	MP_AUTONOTE_ANSWER_SYN,			
	MP_AUTONOTE_ANSWER_ACK,		
	MP_AUTONOTE_ANSWER_NACK,		
	MP_AUTONOTE_ANSWER_FAIL,		
	MP_AUTONOTE_ANSWER_TIMEOUT,		
	MP_AUTONOTE_ANSWER_LOGOUT,		
	MP_AUTONOTE_NOTAUTO,			
	MP_AUTONOTE_KILLAUTO,			
	MP_AUTONOTE_DISCONNECT,			
	MP_AUTONOTE_LIST_ADD,			
	MP_AUTONOTE_LIST_ALL,			
	MP_AUTONOTE_PUNISH,				
	MP_AUTONOTE_ASKTOAUTO_IMAGE,
};
enum MP_PROTOCOL_SINGED
{//[签到系统][By:十里坡剑神][QQ:112582793][2018/1/4]
	MP_SINGED_GETGIFT_SYN,
	MP_SINGED_GETGIFT_ACK,
	MP_SINGED_INFO_SEND_ACK,
};
enum MP_PROTOCOL_RECHARGE
{//[充值礼包][By:十里坡剑神][QQ:112582793][2018/1/31]
	MP_RECHARGE_SYN,
	MP_RECHARGE_ACK,
	MP_RECHARGE_NACK,
};
enum MP_PROTOCOL_KILLTOPLISTINFO
{//[击杀排行信息][By:十里坡剑神][QQ:112582793][2018/4/23]
	MP_KILLTOPLIST_SYN,
	MP_KILLTOPLIST_ACK,
	MP_KILLTOPLIST_NACK,
	MP_KILLTOPLIST_SEND_ACK,
};
enum MP_PROTOCOL_FORTWAR
{
	MP_FORTWAR_INFO,
	MP_FORTWAR_START_BEFORE10MIN,
	MP_FORTWAR_START,	
	MP_FORTWAR_ING,
	MP_FORTWAR_END,
	MP_FORTWAR_START_BEFORE10MIN_TO_MAP,
	MP_FORTWAR_START_TO_MAP,
	MP_FORTWAR_ING_TO_MAP,
	MP_FORTWAR_END_TO_MAP,

	MP_FORTWAR_ENGRAVE_START_SYN,
	MP_FORTWAR_ENGRAVE_START_ACK,
	MP_FORTWAR_ENGRAVE_START_NACK,

	MP_FORTWAR_ENGRAVE_CANCEL_SYN,
	MP_FORTWAR_ENGRAVE_CANCEL_ACK,
	MP_FORTWAR_ENGRAVE_CANCEL_NACK,

	MP_FORTWAR_ENGRAVE_SUCESS,
	MP_FORTWAR_ENGRAVE_FAIL,

	MP_FORTWAR_WAREHOUSE_INFO_SYN,						
	MP_FORTWAR_WAREHOUSE_INFO_ACK,
	MP_FORTWAR_WAREHOUSE_INFO_NACK,
	MP_FORTWAR_WAREHOUSE_LEAVE,

	MP_FORTWAR_SIEGEWAREHOUSE_INFO_SYN,					
	MP_FORTWAR_SIEGEWAREHOUSE_INFO_ACK,
	MP_FORTWAR_SIEGEWAREHOUSE_INFO_NACK,
	MP_FORTWAR_SIEGEWAREHOUSE_LEAVE,

	MP_FORTWAR_WAREHOUSE_ITEM_MOVE_SYN,						
	MP_FORTWAR_WAREHOUSE_ITEM_MOVE_ACK,
	MP_FORTWAR_WAREHOUSE_ITEM_MOVE_NACK,
	MP_FORTWAR_WAREHOUSE_ITEM_MOVE_TO_SIEGEHOUSE_SYN,

	MP_FORTWAR_SIEGEWAREHOUSE_ITEM_MOVE_SYN,				
	MP_FORTWAR_SIEGEWAREHOUSE_ITEM_MOVE_ACK,
	MP_FORTWAR_SIEGEWAREHOUSE_ITEM_MOVE_NACK,

	MP_FORTWAR_WAREHOUSE_ITEM_INSERT,						
	MP_FORTWAR_WAREHOUSE_ITEM_INSERT_TO_MAP,				

	MP_FORTWAR_WAREHOUSE_ITEM_MOVE_TO_INVEN,				
	MP_FORTWAR_WAREHOUSE_ITEM_MOVE_TO_INVEN_TO_MAP,			
	MP_FORTWAR_WAREHOUSE_ITEM_MOVE_TO_SIEGEHOUSE,			
	MP_FORTWAR_WAREHOUSE_ITEM_MOVE_TO_SIEGEHOUSE_TO_MAP,	

	MP_FORTWAR_SIEGEWAREHOUSE_ITEM_MOVE_TO_INVEN,			
	MP_FORTWAR_SIEGEWAREHOUSE_ITEM_MOVE_TO_INVEN_TO_MAP,	

	MP_FORTWAR_WAREHOUSE_PUTOUT_MONEY_SYN,
	MP_FORTWAR_WAREHOUSE_PUTOUT_MONEY_ACK,
	MP_FORTWAR_WAREHOUSE_PUTOUT_MONEY_NACK,
	MP_FORTWAR_WAREHOUSE_MONEY_TO_MAP,

	MP_FORTWAR_SIEGEWAREHOUSE_PUTOUT_MONEY_SYN,
	MP_FORTWAR_SIEGEWAREHOUSE_PUTOUT_MONEY_ACK,
	MP_FORTWAR_SIEGEWAREHOUSE_PUTOUT_MONEY_NACK,


	MP_FORTWAR_DROPITEM_TO_FORTWAREHOUSE,					
};
//////////////////////////////////////////////////////////////////////////

enum MP_TOOLPROC_CONNECT
{
	MP_RMTOOL_CONNECT_SYN,
	MP_RMTOOL_CONNECT_ACK,
	MP_RMTOOL_CONNECT_NACK,
	
	MP_CHECKIP_ERROR,
};

enum MP_TOOLPROC_USER
{
	MP_RMTOOL_USERSEARCH_SYN,
	MP_RMTOOL_USERSEARCH_ACK,
	MP_RMTOOL_USERSEARCH_NACK,
	
	MP_RMTOOL_SIMPLECHARACTER_SYN,
	MP_RMTOOL_SIMPLECHARACTER_ACK,
	MP_RMTOOL_SIMPLECHARACTER_NACK,
	
	MP_RMTOOL_QUERY_MEMBERNUM_SYN,
	MP_RMTOOL_QUERY_MEMBERNUM_ACK,
	MP_RMTOOL_QUERY_MEMBERNUM_NACK,
	
	MP_RMTOOL_CHECKNAME_SYN,
	MP_RMTOOL_CHECKNAME_ACK,
	MP_RMTOOL_CHECKNAME_NACK,

	MP_RMTOOL_CHARACTER_RECOVER_SYN,
	MP_RMTOOL_CHARACTER_RECOVER_ACK,
	MP_RMTOOL_CHARACTER_RECOVER_NACK,
	
	MP_RMTOOL_CHARACTER_CREATEINFO_SYN,
	MP_RMTOOL_CHARACTER_CREATEINFO_ACK,
	MP_RMTOOL_CHARACTER_CREATEINFO_NACK,

	MP_RMTOOL_CHANGE_USERLEVEL_SYN,
	MP_RMTOOL_CHANGE_USERLEVEL_ACK,
	MP_RMTOOL_CHANGE_USERLEVEL_NACK,
};

enum MP_TOOLPROC_CHARACTER
{
	MP_RMTOOL_CHARACTERINFO_SYN,
	MP_RMTOOL_CHARACTERINFO_NACK,

	MP_RMTOOL_CHARACTER_BASEINFO,
	MP_RMTOOL_CHARACTER_INVENINFO,
	MP_RMTOOL_CHARACTER_PYOGUKINFO,
	MP_RMTOOL_CHARACTER_PYOGUKITEMINFO,
	MP_RMTOOL_CHARACTER_MUGONGINFO,
	MP_RMTOOL_CHARACTER_ABILLITYINFO,
	
	MP_RMTOOL_CHARACTER_UPDATE_BASEINFO,
	MP_RMTOOL_CHARACTER_UPDATE_PYOGUKINFO,
	MP_RMTOOL_CHARACTER_UPDATE_ABILLITYINFO,

	MP_RMTOOL_CHARACTERINFO_ITEMOPTIONINFO,

	MP_RMTOOL_CHARACTER_INSERTMUGONG,
	MP_RMTOOL_CHARACTER_UPDATEMUGONG,
	MP_RMTOOL_CHARACTER_DELETEMUGONG,
	
	MP_RMTOOL_CHARACTER_MAINQUESTINFO_SYN,
	MP_RMTOOL_CHARACTER_MAINQUESTINFO_ACK,
	MP_RMTOOL_CHARACTER_MAINQUESTDELETE,

	MP_RMTOOL_CHARACTER_SUBQUESTINFO_SYN,
	MP_RMTOOL_CHARACTER_SUBQUESTINFO_ACK,	
	
	MP_RMTOOL_CHARACTER_CHANGE_LOGINPOINT_SYN,
	MP_RMTOOL_CHARACTER_CHANGE_LOGINPOINT_ACK,
	MP_RMTOOL_CHARACTER_CHANGE_LOGINPOINT_NACK,

	MP_RMTOOL_CHARACTER_INVENINFO2,
	MP_RMTOOL_CHARACTER_MUGONGINFO2,
	
	MP_RMTOOL_CHANGE_ITEMPOSITION,
	MP_RMTOOL_CHANGE_WAREITEMPOSITION,
	MP_RMTOOL_CHANGE_MUGONGPOSITION,
	
	MP_RMTOOL_CHARACTER_SHOPWARE_ITEMINFO,

	MP_RMTOOL_CHARACTERINFO_RAREITEMOPTIONINFO,

	MP_RMTOOL_CHARACTER_USINGSHOPITEMINFO_SYN,
	MP_RMTOOL_CHARACTER_USINGSHOPITEMINFO_ACK,

	MP_RMTOOL_CHARACTER_USINGSHOPITEMINFO_DELETE_SYN,
	MP_RMTOOL_CHARACTER_USINGSHOPITEMINFO_EDIT_SYN,

	MP_RMTOOL_CHARACTER_MAINPETLIST_SYN,
	MP_RMTOOL_CHARACTER_MAINPETLIST_ACK,
};

enum MP_TOOLPROC_ITEM
{
	MP_RMTOOL_INSERTITEM,
	MP_RMTOOL_UPDATEITEM,
	MP_RMTOOL_DELETEITEM,
};

enum MP_TOOLPROC_MUNPA
{
	MP_RMTOOL_GUILD_SYN,	
	MP_RMTOOL_GUILD_ACK,
	MP_RMTOOL_GUILD_NACK,

	MP_RMTOOL_GUILDIFNO_SYN,
	MP_RMTOOL_GUILDIFNO_NACK,

	MP_RMTOOL_GUILDBASEIFNO,
	MP_RMTOOL_GUILDMEMBERIFNO,
	MP_RMTOOL_GUILDITEMIFNO,
	MP_RMTOOL_GUILDITEMOPTIONIFNO,

	MP_RMTOOL_MUNPASEARCH_SYN,
	MP_RMTOOL_MUNPASEARCH_NACK,

	MP_RMTOOL_MUNPAINFO_RESYN,
	MP_RMTOOL_MUNPAINFO_NACK,

	MP_RMTOOL_MUNPABASEINFO,
	MP_RMTOOL_MUNPAITEMINFO,
	MP_RMTOOL_MUNPAMEMBERINFO,

	MP_RMTOOL_MUNPAMONEYUPDATE,
};

enum MP_TOOLPROC_GAMELOG
{
	MP_RMTOOL_GAMELOGSEARCH_SYN,
	MP_RMTOOL_GAMELOGSEARCH_NACK,

	MP_RMTOOL_QUERY_CHARIDX_SYN,
	MP_RMTOOL_QUERY_CHARIDX_ACK,
	MP_RMTOOL_QUERY_CHARIDX_NACK,
	
	MP_RMTOOL_ITEMMONEYLOGFROMTYPE_SYN,
	MP_RMTOOL_ITEMMONEYLOGFROMTYPE_ACK,
	
	MP_RMTOOL_CHARACTERLOG_SYN,
	MP_RMTOOL_CHARACTERLOG_ACK,

	MP_RMTOOL_EXPPOINTLOG_SYN,
	MP_RMTOOL_EXPPOINTLOG_ACK,

	MP_RMTOOL_MUGONGLOG_SYN,
	MP_RMTOOL_MUGONGLOG_ACK,

	MP_RMTOOL_MUGONGEXPLOG_SYN,
	MP_RMTOOL_MUGONGEXPLOG_ACK,	

	MP_RMTOOL_MONEYLOG_SYN,
	MP_RMTOOL_MONEYLOG_ACK,

	MP_RMTOOL_MONEYWRONGLOG_SYN,
	MP_RMTOOL_MONEYWRONGLOG_ACK,

	MP_RMTOOL_ABILITYLOG_SYN,
	MP_RMTOOL_ABILITYLOG_ACK,	
	
	MP_RMTOOL_CHEATLOG_SYN,
	MP_RMTOOL_CHEATLOG_ACK,

	MP_RMTOOL_HACKINGLOG_SYN,
	MP_RMTOOL_HACKINGLOG_ACK,
	
	MP_RMTOOL_TOOLLOG_SYN,
	MP_RMTOOL_TOOLLOG_ACK,

	MP_RMTOOL_ITEMOPTIONLOG_SYN,
	MP_RMTOOL_ITEMOPTIONLOG_ACK,

	MP_RMTOOL_PETLOGFROMTYPE_SYN,
	MP_RMTOOL_PETLOGFROMTYPE_ACK,

	MP_RMTOOL_QUERY_GUILDTNIDX_SYN,
	MP_RMTOOL_QUERY_GUILDTNIDX_ACK,
	MP_RMTOOL_QUERY_GUILDTNIDX_NACK,
	
	MP_RMTOOL_GUILDTNLOGFROMTYPE_SYN,
	MP_RMTOOL_GUILDTNLOGFROMTYPE_ACK,

	MP_RMTOOL_QUERY_SIEGEWARIDX_SYN,
	MP_RMTOOL_QUERY_SIEGEWARIDX_ACK,
	MP_RMTOOL_QUERY_SIEGEWARIDX_NACK,
	
	MP_RMTOOL_SIEGEWARLOGFROMTYPE_SYN,
	MP_RMTOOL_SIEGEWARLOGFROMTYPE_ACK,

	MP_RMTOOL_GMTOOLLOGFROMTYPE_SYN,
	MP_RMTOOL_GMTOOLLOGFROMTYPE_ACK,

};

enum MP_TOOLPROC_ADMIN
{
	MP_RMTOOL_ADMIN_TOTALINFO_SYN,
	MP_RMTOOL_ADMIN_TOTALINFO_NACK,

	MP_RMTOOL_ADMIN_OPERATORINFO,
	MP_RMTOOL_ADMIN_IPINFO,

	MP_RMTOOL_ADMIN_INSERTOPERATOR_SYN,
	MP_RMTOOL_ADMIN_INSERTOPERATOR_ACK,
	MP_RMTOOL_ADMIN_INSERTOPERATOR_NACK,

	MP_RMTOOL_ADMIN_INSERTIP_SYN,
	MP_RMTOOL_ADMIN_INSERTIP_ACK,
	MP_RMTOOL_ADMIN_INSERTIP_NACK,

	MP_RMTOOL_ADMIN_DELETEOPERATOR_SYN,
	MP_RMTOOL_ADMIN_DELETEIP_SYN,
	
	MP_RMTOOL_ADMIN_GMIPINFO,

	MP_RMTOOL_ADMIN_INSERTGMIP_SYN,
	MP_RMTOOL_ADMIN_INSERTGMIP_ACK,
	MP_RMTOOL_ADMIN_INSERTGMIP_NACK,

	MP_RMTOOL_ADMIN_DELETEGMIP_SYN,
};

enum MP_TOOLPROC_PET
{
	MP_RMTOOL_PETSEARCH_SYN = 10,
	MP_RMTOOL_PETSEARCH_ACT,
	MP_RMTOOL_PETSEARCH_NACK,

	MP_RMTOOL_PETITEMIFNO,

	MP_RMTOOL_PETLIST,
	MP_RMTOOL_PETLIST_SYN,

	MP_RMTOOL_PETLIST_ACT,
	MP_RMTOOL_PETLIST_NACK,

	MP_RMTOOL_PETACCIFNO,

	MP_RMTOOL_PET_UPDATE_BASEINFO,
	MP_RMTOOL_PETUSERLOGINCHK,

	MP_RMTOOL_PET_MEMBERNUM_NACK,
	MP_RMTOOL_PET_MEMBERNUM_ACK,

	MP_RMTOOL_PET_MEMBERNUM_SYN,

};

enum MP_TOOLPROC_DELCHAR
{
	MP_RMTOOL_DELCHARLIST_SYN = 10,
	MP_RMTOOL_DELCHARLIST_ACT,
	MP_RMTOOL_DELCHARLIST_NACK,

};
//[安全锁][By:十里坡剑神][QQ:112582793][2018/4/30]
enum MP_PROTOCOL_SAFELOCK
{
	MP_SAFELOCK_UNLOCK_SYN,
	MP_SAFELOCK_UNLOCK_ACK,
	MP_SAFELOCK_UNLOCK_NACK,

	MP_SAFELOCK_RESTPWD_SYN,
	MP_SAFELOCK_RESTPWD_ACK,
	MP_SAFELOCK_RESTPWD_NACK,

	MP_SAFELOCK_UNLOCK_AGTOMAP_SYN,
	MP_SAFELOCK_LOCKEDTOCLIENT_ACK,

	MP_SAFELOCK_RELOCK_SYN,
};
enum MP_PROTOCOL_REDISCONNECT
{
	RE_DIS_CONNECT_MAINTAINACE,//[维护通知][By:十里坡剑神][QQ:112582793][2018/6/12]
	RE_DIS_CONNECT_UPDATE,	   //[更新重连通知][By:十里坡剑神][QQ:112582793][2018/6/12]
	RE_DIS_CONNECT_ACK,		   //[重连通知][By:十里坡剑神][QQ:112582793][2018/6/12]
	RE_DIS_CONNECT_NACK,	   //[重连失败通知][By:十里坡剑神][QQ:112582793][2018/6/12]	
	RE_DIS_CONNECT_READY,	   //[重连服务器连接成功][By:十里坡剑神][QQ:112582793][2018/6/13]
};
#endif // __PROTOCOL_H__


